// 主程序端的文案:orchestrator 的系統訊息、給成員的提示詞、附件提示、匯出的 Markdown。
// 介面文案在 renderer/i18n.ts;這裡只放 renderer 看不到、由主程序組出的字串。
// 繁體中文是原始文案,英文是對應翻譯。AGREED / NO_ISSUES 這類標記是協定,不翻譯。

export type TextLocale = 'zh-Hant' | 'en';
type Params = Record<string, string | number>;
type Entry = string | ((p: Params) => string);

// 作業系統語系。Electron 主程序的 Intl 預設是 en-US、不看系統語言,所以 main.ts 啟動時
// 用 app.getLocale() 設定這個值;測試環境沒有 Electron,退回 Intl。
let systemLocaleTag = '';
export function setSystemLocale(tag: string): void { systemLocaleTag = tag || ''; }

// 設定值 'system'(或沒設定)時跟著作業系統
export function resolveTextLocale(setting: string | null | undefined): TextLocale {
  if (setting === 'zh-Hant' || setting === 'en') return setting;
  let system = systemLocaleTag;
  if (!system) { try { system = Intl.DateTimeFormat().resolvedOptions().locale || ''; } catch {} }
  return system.toLowerCase().startsWith('zh') ? 'zh-Hant' : 'en';
}

const ZH: Record<string, Entry> = {
  'api.missingKeyEnv': '缺少 API key:請到「設定 → CLI 與擴充」填入,或設定環境變數 {env}',
  'api.missingKey': '缺少 API key:請到「設定 → CLI 與擴充」填入並儲存',
  'api.invalidKey': 'API key 被 {service} 拒絕:請到「設定 → CLI 與擴充」重新填入',
  'api.service': '服務',
  'api.modelsTimeout': '取得模型清單逾時',
  'api.connectionTimeout': '測試連線逾時',
  'api.connected': '已連線 {url}',
  'api.networkHint': '連不上服務:請確認網路,或稍後再試',
  'api.localHint': '請確認服務已啟動並可連線',
  'api.noModel': '沒有指定模型:請在成員設定選擇模型,或在擴充設定填 defaultModel',
  'api.runTimeout': 'API 執行逾時({duration})',
  'api.stopped': '已停止',
  'api.cannotConnect': '無法連線到 {url}:{error}',
  'api.fileToolsFailed': '無法啟用檔案工具:{error}',
  'api.tooManyTools': '這批工具呼叫會超過每回合 {n} 次上限，整批未執行；請減少呼叫數',
  'api.toolRunning': '{name} 執行中',
  'api.readToolsFallback': '帶工具的請求被拒絕({error}),改成不帶工具重送一次',
  'api.ephemeralDropped': '(這裡原本附上的檔案內容只用於那一回合,已從記憶中移除)',
  'api.readToolsUnavailable': '(這個模型這次無法使用 read_file 工具。請不要呼叫任何工具,只依上面提示詞裡的內容作答。)',
  'api.toolRoundsExceeded': '模型工具呼叫往返超過 {n} 次，已停止以避免無限循環',
  'api.imageFallback': '此模型不接受圖片({error}),已略過 {n} 張圖片改用純文字重送',
  'api.startOllama': '請先啟動 Ollama',
  'api.ollamaTestFailed': '無法測試 Ollama 連線',
  'api.ollamaConnectFailed': '無法連線到 Ollama',
  // ---------- 系統訊息 ----------
  'sys.error': '發生錯誤:{message}',
  'sys.noAgents': '沒有啟用的成員,請先在左側新增或啟用成員。',
  'sys.cwdFailed': '無法建立工作目錄 {cwd}:{message}',
  'sys.stopped': '已停止。',
  'sys.stageFailed': '附件無法複製到工作目錄:{error}',
  'sys.unstageFailed': '無法清除工作目錄的附件暫存({dir}):{error}',
  'sys.agreed': '第 {round} 回合全員達成共識。',
  'sys.askAnswered': '回答 {name} 的提問:\n{answer}',
  'sys.askDeferred': '{name} 的提問由你們自行決定,請依你們的判斷繼續。',
  'sys.maxRoundsDivide': '已達最大討論回合({max}),直接進入分工。',
  'sys.maxRoundsSummary': '已達最大討論回合({max}),由主持人總結。',
  'sys.unmatched': '**有工作無法對應到成員**,已跳過:\n{list}',
  'sys.plan': (p) => `**分工結果**${p.summary ? `:${p.summary}` : ''}\n\n${p.lines}`,
  'sys.planNoMatch': '主持人的分工沒有任何一項能對應到成員,再試一次。',
  'sys.planUnparsable': '主持人輸出的分工格式無法解析,再試一次。',
  // 主持人整個回合就失敗時(CLI 沒安裝、key 失效、逾時),說「格式無法解析」會把使用者
  // 指向錯的地方:要修的是主持人這位成員,不是它的輸出格式。
  'sys.planLeadFailed': '主持人「{name}」沒有回應,無法產生分工。請檢查這位成員的設定(左下角的狀態列可以直接開啟)。',
  'sys.planFailed': '分工失敗,已中止分工與執行。可以改用「只討論」模式,或換一位主持人再試一次。',
  'sys.nobodyAssigned': '沒有任何成員被分配到工作。',
  'sys.execFailed': '**執行失敗**,這些成員的成果不會進入審查:\n{list}',
  'sys.noReport': '沒有產生回報',
  'sys.noReviewer': '找不到可以擔任審查者的其他成員(整場只有一名啟用成員),略過交叉審查。',
  'sys.toolAudit': (p: Params) => `**${p.name} 的檔案操作**\n${p.list}`,
  'sys.toolUnknownError': '未知錯誤',
  'sys.toolStatsApprox': ',為近似值,請以實際檔案改動為準',
  'sys.reviewFailed': '**交叉審查失敗**,這些審查沒有結果,不代表被審查的成果沒有問題:\n{list}',
  'sys.reviewFailedItem': '- **{reviewer}** 審查「{target}」:{error}',
  'sys.noReviewText': '沒有產生審查意見',
  'sys.noSuccessfulReview': '沒有任何成功的審查意見,略過修復回合。',
  'sys.noIssues': '交叉審查沒有發現問題,略過修復回合。',
  'sys.unresolved': '「{names}」沒有修改檔案的權限,審查意見將直接帶入總結。',
  'sys.fixFailed': '**修復失敗**,以下成員的審查意見仍未處理:\n{list}',
  'sys.retryBusy': '目前有任務進行中,請等它結束再重試。',
  'sys.retryNotAllowed': '這則訊息無法重試(只有最近一次失敗的指定回覆可以重試)。',
  'sys.unfinishedOnSave': '這則訊息在儲存時尚未完成',

  // ---------- 對話紀錄 ----------
  'transcript.new': '【新訊息】',
  'transcript.sofar': '【目前為止的對話紀錄】',
  'transcript.user': '使用者',
  'transcript.system': '系統',
  'transcript.omitted': '…(已省略中間 {n} 則訊息)…',
  'transcript.clipped': '\n…(此則訊息過長,已截斷)…',

  // ---------- 提示詞 ----------
  'prompt.system.intro': '你是名為「{name}」的 AI 助理,正在一個多 AI 圓桌會議中與其他 AI 助理({others})協作,由使用者主持。',
  'prompt.system.noOthers': '(目前沒有其他成員)',
  'prompt.system.persona': '你的角色與個性:{persona}',
  'prompt.system.noPersona': '(未設定)',
  'prompt.system.rules': '規則:',
  'prompt.system.rule1': '- 使用{lang}回覆,簡潔、有重點,不要重複別人已經說過的內容。',
  'prompt.system.rule2': '- 對其他成員的看法要具體回應:同意、反對(附理由)或補充。有分歧時要明確說出自己的立場。',
  'prompt.system.rule3': '- 訊息中以「[名稱]:」開頭的段落是其他成員或使用者說的話。你自己的回覆不要加名稱前綴,直接寫內容。',
  'prompt.system.agreed': '- 討論階段中,若你認為已有足夠共識、可以進入分工執行,請在回覆最後單獨一行寫上 {mark}。尚未有共識就不要寫。只有單獨成行才算數,在句子裡提到它不會被視為同意。',
  'prompt.system.ask': '- 討論階段中,若遇到必須由使用者決定、你無法自行判斷的關鍵問題,可以在回覆最後加一個提問區塊:單獨一行寫 {open},接著一行問題,再用「- 」條列 2~4 個可選答案,最後單獨一行寫 {close}。整場討論最多問 {max} 次,同一回合只會受理一題,不重要的事不要問,先把不需要答案就能做的部分講完。',
  'prompt.system.act': '- 執行與審查階段請根據指示實際操作,不要只給建議。',

  'prompt.task': '【任務】\n{task}\n',
  'prompt.discussLast': '這是最後一回合討論,請收斂並給出你的最終立場。若同意進入分工請在最後單獨一行寫 {mark}。',
  'prompt.discuss': '請發表你的看法(第 {round}/{max} 回合)。若你認為已可進入分工執行,請在最後單獨一行寫 {mark}。',

  'prompt.directed': '【指定回覆】使用者在最新一則訊息中用 @ 指定由你處理,請直接回應或完成使用者的要求。',
  'prompt.directedOthers': '同時被指定的還有 {others},各自處理即可,不需要等待對方。',
  'prompt.directedAlone': '這次只有你被指定,其他成員不會發言。',
  'prompt.directedCanEdit': '需要時可以直接在工作目錄({cwd})建立、修改檔案與執行指令。',
  'prompt.directedReadOnly': '你目前沒有修改檔案的權限,需要改動時請寫出完整內容或步驟。',

  'prompt.assign': '【分工】你是本次的主持人。請根據到目前為止的討論結果,把任務拆解並分配給以下成員:',
  'prompt.rosterItem': '- {code} =「{name}」({label}{readonly})',
  'prompt.rosterReadOnly': ',唯讀,不能修改檔案',
  'prompt.assignNoOverlap': '每位成員負責的檔案或模組盡量不要重疊,以免同時修改造成衝突。可以把某位成員的工作留空(不分配)。',
  'prompt.assignCodes': '`agent` 欄位請填上面的代號({codes}),不要填名稱。',
  'prompt.assignJson': '只輸出一段 JSON,不要加任何說明或 markdown 標記,格式如下:',
  'prompt.assignExample': '{"summary":"一句話說明整體方案","assignments":[{"agent":"A1","task":"具體、可直接執行的工作說明,包含要建立或修改的檔案"}]}',
  'prompt.unmatchedItem': '- `{agent}`:{task}',
  'prompt.planItem': '- **{name}**:{task}',

  'prompt.execute': '【執行】以下是分配給你的工作,請現在實際完成它(工作目錄:{cwd})。',
  'prompt.executeCanEdit': '你可以直接建立、修改檔案與執行指令。',
  'prompt.executeReadOnly': '注意:你目前沒有修改檔案的權限,請把要做的內容以完整程式碼或步驟寫出來。',
  'prompt.executeReport': '完成後請簡潔回報:做了什麼、建立或修改了哪些檔案、有什麼未完成或需要別人配合的地方。',
  'prompt.failedItem': '- **{name}**:{error}',

  'prompt.review': '【交叉審查】請檢查「{name}」剛完成的工作。請實際打開相關檔案確認,不要只看回報。',
  // 審查者無法自己讀檔時用這個版本:說清楚它看不到檔案,改動內容附在下面。
  // 以前對所有人都說「請打開檔案」,沒有工具的模型只好把工具呼叫當成文字寫出來假裝讀了。
  'prompt.reviewInline': '【交叉審查】請檢查「{name}」剛完成的工作。你沒有辦法自己打開檔案,所以下面附上了改動檔案目前的實際內容。請依這些內容確認,不要只看回報,也不要對沒附上的部分下結論。',
  'prompt.reviewReadTool': '下面沒附上的檔案、或被省略的部分,可以用 read_file 工具讀取。',
  // 工作目錄前後沒有差異(例如只做分析的任務)。只說「工作目錄裡沒偵測到」:略過的目錄與工作目錄以外都看不到。
  'prompt.reviewNoChanges': '【交叉審查】請檢查「{name}」剛完成的工作。這次工作目錄裡沒有偵測到檔案改動(不含 .git、node_modules 等目錄),請依任務與回報審查;若任務需要修改工作目錄裡的檔案卻沒有改,也請指出。',
  'prompt.reviewNoFilesChanged': '這次工作目錄裡沒有偵測到檔案改動(不含 .git、node_modules 等目錄)。若任務需要修改工作目錄裡的檔案卻沒有改,請指出。',
  'prompt.reviewAttached': '【交叉審查】請檢查「{name}」剛完成的工作。下面附上了改動檔案目前的實際內容,請依這些內容確認,不要只看回報。',
  'prompt.reviewUntouched': '【交叉審查】請檢查「{name}」剛完成的工作。依檔案工具的紀錄,「{name}」這次沒有修改任何檔案,請依任務與回報審查;若任務需要修改檔案卻沒有改,也請指出。',
  'prompt.reviewUntouchedLine': '依檔案工具的紀錄,「{name}」這次沒有修改任何檔案。若任務需要修改檔案卻沒有改,請指出。',
  'prompt.reviewReadOnly': '【交叉審查】請檢查「{name}」剛完成的工作。「{name}」這次沒有修改檔案的權限,它的工作不會改動檔案,請依任務與回報審查。',
  'prompt.reviewFilesAll': '這次任務所有執行成員改動的檔案(不一定都是「{name}」改的,請對照它的任務與回報):\n{list}',
  'prompt.reviewReadToolAny': '你可以用 read_file 工具讀取工作目錄裡的檔案,核對回報的內容。',
  'prompt.reviewReadToolUnlisted': '你可以用 read_file 工具讀取工作目錄裡的檔案。這次無法自動確定改了哪些檔案,請依任務與回報中提到的檔案自行讀取,實際讀過再下判斷;如果沒辦法讀到檔案,請說明無法驗證的部分,並且不要寫 {mark}。',
  'prompt.reviewInlineUnknown': '【交叉審查】請檢查「{name}」剛完成的工作。你沒有辦法自己打開檔案,這次也無法取得改動的檔案內容,所以你看不到實際的改動。請不要只憑回報判定沒有問題:說明你無法驗證哪些部分,並且不要寫 {mark}。',
  'prompt.reviewWhat': '指出:明確的錯誤、與討論結論不一致之處、可以改進的地方。請簡潔。',
  'prompt.reviewFiles': '這次改動的檔案:\n{list}',
  'prompt.reviewContent': '改動檔案目前的內容:',
  'prompt.reviewFileBlock': '----- {path} -----\n{content}',
  'prompt.reviewFileUnreadable': '----- {path} -----\n(無法讀取:{error})',
  'prompt.reviewOmitted': '下面這些改動的檔案超過附上的數量或長度上限,沒有附上內容:\n{list}\n請不要對它們下結論,並在回覆中說明哪些部分因此無法驗證。',
  'prompt.reviewTruncated': '\n…(檔案過長,後面省略)…',
  'prompt.reviewMark': '若你確認完全沒有問題,請在回覆的最後單獨一行寫上 {mark};只要有任何一項需要修正就不要寫。',
  'prompt.reviewTask': '他負責的工作:\n{task}',
  'prompt.reviewReport': '他的回報:\n{report}',
  'prompt.reviewNote': '[{reviewer}]:\n{text}',

  'prompt.fix': '【修復】以下是其他成員對你剛才成果的審查意見。請現在就處理:能修的直接改檔案,不打算修的要明確說明理由。',
  'prompt.fixLast': '這是最後一輪修改,之後不會再審查。請簡潔回報你改了什麼、哪些沒改以及為什麼。',
  'prompt.fixTask': '你負責的工作:\n{task}',
  'prompt.fixNotes': '審查意見:\n{notes}',
  'prompt.fixFailedItem': '- **{name}**:{error}',

  'prompt.summary.failed': '以下成員的執行失敗,成果未納入審查,請在總結中明確指出:\n{list}',
  'prompt.summary.failedItem': '- {name}:{error}',
  'prompt.summary.reviewFailed': '以下交叉審查沒有完成,對應的成果等於沒有被檢查過,請在總結中明確標示為「未經審查」,不要說成沒有問題:\n{list}',
  'prompt.summary.reviewFailedItem': '- {reviewer} 審查 {target}:{error}',
  'prompt.summary.fixFailed': '以下成員的修復回合失敗,審查指出的問題仍然存在,請在總結中列為未解決:\n{list}',
  'prompt.summary.fixFailedItem': '- {name}:{error}\n  未處理的審查意見:\n{notes}',
  'prompt.summary.unresolved': '以下成員沒有修改檔案的權限,審查意見尚未處理,請在總結中列出並說明需要使用者做什麼:\n{list}',
  'prompt.summary.unresolvedItem': '- {name}:\n{notes}',
  'prompt.summary.git': '執行結束時,工作目錄的 git 變更如下。這是**當下的工作區狀態**,可能包含本次任務開始前就已存在的變更,請據實轉述、不要宣稱這些變更全部由本次任務產生:\n{changes}',
  'prompt.summary.divide': '【總結】請以主持人身分,根據執行回報、交叉審查與修復結果,簡潔總結:完成了什麼、審查發現並修掉了什麼、還有哪些未解決或需要使用者決定的事項。',
  'prompt.summary.discuss': '【總結】請以主持人身分,簡潔總結這次討論的結論、分歧點,以及建議的下一步。',
  'git.more': '- (另有 {n} 個變更檔案未列出)',
  'git.preexisting': '(執行前就已是變更狀態)',

  // ---------- 附件提示 ----------
  'attach.header': '【附件】使用者提供了 {n} 個附件:',
  'attach.path': '- {label}\n  路徑:{path}',
  'attach.imageInline': '- {label}(影像已隨訊息附上)',
  'attach.textInline': '- {label}(內容如下)',
  'attach.inlineCap': '- {label}(已達文字附件總內嵌上限,內容省略)',
  'attach.truncated': '\n…(檔案過長或已達附件總量上限,已截斷;完整內容見原始檔案)…',
  'attach.unreadable': '注意:你無法讀取 {names} 的內容,請不要憑檔名臆測,必要時請在回覆中說明。',

  // ---------- 匯出 ----------
  'export.title': '# AI Roundtable 對話',
  'export.user': '使用者',
  'export.agent': 'AI 成員',
  'export.system': '系統',
  'export.systemError': '系統錯誤',
  'export.systemWarn': '系統警告',
  'export.timeUnknown': '時間不明',
  'export.rawUsage': '> 原始用量：{fields}',
  'export.noFields': '無欄位',
  'export.usage': '> 用量：{fields}',
  'export.input': '輸入: {n}',
  'export.cached': '其中快取 {n}',
  'export.cacheWrite': '寫入快取 {n}',
  'export.cachedInput': '快取輸入: {n}',
  'export.output': '輸出: {n}',
  'export.cost': '成本: ${n}',
  'export.attachments': '> 附件：{list}',
  'export.unreviewed': '> ⚠ 尚未審查：這次改動沒有其他成員看過，請自行確認紅綠 diff。',
  'export.error': '> 錯誤：{text}',
  'export.empty': '_(無文字內容)_',
  'phase.idle': '閒置', 'phase.direct': '指定', 'phase.discuss': '討論', 'phase.divide': '分工',
  'phase.execute': '執行', 'phase.review': '審查', 'phase.repair': '修復', 'phase.summary': '總結',

  // ---------- 主程序 ----------
  'main.extNotFound': '找不到此 API 擴充，請先儲存設定',
  'main.extNoTest': '此擴充不支援 API 連線測試',
  'main.nothingToExport': '目前沒有可匯出的對話',
  'main.exportTitle': '匯出本次對話',
  'main.stillRunning': '目前仍在進行中,請先停止再載入歷史對話',
  'main.attachFilter': '可用附件',
  'adapter.missing': '找不到 CLI「{cli}」:對應的擴充可能已刪除或載入失敗,請到「設定 → CLI 與擴充」檢查',
  'adapter.failed': '{label} 執行失敗:{message}',
  // ---------- CLI 成員的執行期訊息 ----------
  // 這些會直接出現在對話泡泡的錯誤列與工具動作清單裡。錯誤原文(stderr)接在翻譯後面,不翻譯。
  'proc.seconds': '{n} 秒',
  'proc.minutes': '{n} 分鐘',
  'proc.minutesSeconds': '{m} 分 {s} 秒',
  'proc.timeout': '執行逾時({time})',
  'proc.timeoutSigterm': '執行逾時({time}),已送出 SIGTERM。',
  'proc.timeoutSigkill': '逾時行程未結束,已送出 SIGKILL。',
  'proc.notFound': '找不到指令 {bin}',
  'proc.checkTimeout': '逾時',
  'proc.checkSkipped': '(略過檢查)',
  'cli.spawnFailed': '無法啟動 {bin}:{detail}',
  'cli.timedOut': '{bin} 執行逾時',
  'cli.exitCode': '{bin} 結束代碼 {code}',
  'cli.failed': '{name} 執行失敗',
  'cli.reportedError': '{name} 回報錯誤',
  'cli.turnFailed': '{name} 回合失敗',
  'cli.customNotSet': '尚未設定自訂指令',
  'cli.customCommand': '自訂指令',
  'cli.unparsableJson': '無法解析 JSON 輸出:{detail}',
  // 未登入:給一句照做就能修好的話。指令放在 {cmd},介面另有複製按鈕。
  'cli.loginHint': '已安裝,但尚未登入。請開啟「終端機」,執行 {cmd} 並依畫面完成登入。',
  'cli.notLoggedIn': '{name} 尚未登入,或登入已過期。請開啟「終端機」,執行 {cmd} 並依畫面完成登入後再試一次。',
  'act.run': '執行指令:{detail}',
  'act.read': '讀取檔案:{detail}',
  'act.edit': '編輯檔案:{detail}',
  'act.write': '寫入檔案:{detail}',
  'act.delete': '刪除檔案:{detail}',
  'act.glob': '搜尋檔名:{detail}',
  'act.grep': '搜尋內容:{detail}',
  'act.ls': '列出目錄:{detail}',
  'act.tool': '工具:{detail}',
  'act.changes': '修改檔案({n})',
  'act.webSearch': '搜尋網路:{detail}',
  'cursor.effortIgnored': 'Cursor 的強度寫在模型名稱裡,已略過 {effort}',
  // ---------- 附件被拒絕的原因(顯示在輸入框「無法附加檔案:…」) ----------
  // 與上面的 attach.* 不同:那些是寫進提示詞給模型看的。
  'attachErr.notFormat': '內容不是 {fmt} 格式(副檔名與實際內容不符)',
  'attachErr.looksLike': '內容看起來是{kind},不是文字檔',
  'attachErr.nul': '文字檔不可包含 NUL 位元組(內容看起來是二進位檔)',
  'attachErr.utf8': '文字檔必須是有效的 UTF-8 編碼',
  'attachErr.json': '內容不是有效的 JSON 格式(副檔名與實際內容不符)',
  'attachErr.tooBig': '超過單檔上限 {limit}(這個檔 {size})',
  'attachErr.totalTooBig': '超過單次合計上限 {limit}',
  'attachErr.tooMany': '一次最多 {n} 個檔案',
  'attachErr.unsupported': '不支援的檔案類型「{ext}」,目前只收 {list}',
  'attachErr.noExt': '無副檔名',
  'attachErr.empty': '檔案是空的',
  'attachErr.notFile': '不是一般檔案',
  'attachErr.unrecognized': '附件內容格式無法辨識',
  'attachErr.noSource': '缺少檔案內容或路徑',
  'attachErr.badConversation': '無效的對話代號',
  'attachErr.unsafeName': '無法產生安全的儲存檔名',
  'attachErr.exists': '附件儲存路徑已存在',
  'attachErr.unknownSize': '未知大小',
  'attachErr.listSep': '、',
  'bin.elf': 'ELF 執行檔',
  'bin.macho': 'Mach-O 執行檔',
  'bin.machoFat': 'Mach-O 通用二進位',
  'bin.windows': 'Windows 執行檔',
  'bin.zip': 'ZIP / Office 壓縮檔',
  'bin.gzip': 'gzip 壓縮檔',
  // ---------- 歷史對話 ----------
  'session.notTranscript': '內容不是對話紀錄',
  'session.noMessages': '內容不是對話紀錄:缺少 messages 陣列',
  'session.badId': '無效的紀錄代號',
  'session.missing': '這筆紀錄已經不存在(可能已被刪除)',
  // ---------- 擴充的載入、儲存與 Ollama 一鍵設定 ----------
  'ext.duplicateId': 'id「{id}」與 {file} 重複',
  'ext.badJson': 'JSON 格式錯誤:{error}',
  'ext.badJsonUnsaved': 'JSON 格式錯誤,尚未儲存:{error}',
  'ext.badType': 'type 必須是 "cli" 或 "openai"(需要更多彈性時請改寫成 .js 外掛)',
  'ext.noRun': '必須匯出 run(agent, ctx, kit) 函式',
  'ext.badFileName': '檔名只能包含英數字、. _ -,並以 .json 或 .js 結尾',
  'ext.badTemplate': '範本名稱不正確',
  'ext.exists': '已經有名為 {file} 的擴充',
  'ext.noUserDir': '找不到擴充設定目錄',
  'ext.noTemplateDir': '找不到內建 Ollama 範本目錄',
  'ext.ollamaTemplateUnreadable': '無法讀取 Ollama 範本:{error}',
  'ext.ollamaConfigUnreadable': '無法讀取現有 Ollama 設定:{error}',
  'ext.ollamaModelMissing': 'Ollama 找不到模型「{model}」,請先下載後再試一次',
  'ext.noKeychain': '系統安全儲存目前不可用',
  'ext.legacyKeyFailed': '偵測到舊版明文 API key,但{error}。請設定環境變數後移除檔案中的 apiKey',
  'ext.legacyKeyMigrated': '已將舊版明文 API key 移至系統安全儲存。',
  // ---------- 擴充設定的驗證錯誤(寫自訂 JSON 時看到) ----------
  // 句型重複度很高,所以用 {field} 參數化,不逐句翻譯。欄位名稱是協定,不翻譯。
  'spec.contentObject': '內容必須是物件',
  'spec.badId': 'id 必須是 1–64 個英數字,可含 . _ -,且以英數字開頭',
  'spec.modelsShape': 'models 必須是陣列或 "auto"',
  'spec.usageShape': 'usageShape 必須是 {list};不填則依欄位特徵自動判斷',
  'spec.binShape': 'bin 必須是指令名稱或路徑',
  'spec.baseUrl': 'baseUrl 必須是 http:// 或 https:// 開頭的網址',
  'spec.apiKeyEnv': 'apiKeyEnv 必須是環境變數名稱',
  'spec.plainApiKey': 'apiKey 明文欄位已停用,請在擴充設定的 API key 欄位安全移轉',
  'spec.mustBeObject': '{field} 必須是物件',
  'spec.mustBeArray': '{field} 必須是陣列',
  'spec.mustBeString': '{field} 必須是字串',
  'spec.mustBeBoolean': '{field} 必須是布林值',
  'spec.mustBePositive': '{field} 必須是正數',
  'spec.mustBePositiveInt': '{field} 必須是正整數',
  'spec.mustBeOneOf': '{field} 必須是 {list}',
  'spec.onlyAccepts': '{field} 只接受 {list}',
  'spec.noDuplicates': '{field} 不可重複',
  'spec.badFormat': '{field} 格式不正確',
  'spec.badRegex': '{field} 不是有效的正規表示式:{error}',
  'spec.requiresTogether': '{a}=true 時必須明確設定 {b}=true',
  'spec.listSep': '、',
  'spec.or': ' 或 ',
};

const EN: Record<string, Entry> = {
  'api.missingKeyEnv': 'Missing API key: enter it in Settings → CLIs & extensions, or set {env}',
  'api.missingKey': 'Missing API key: enter and save it in Settings → CLIs & extensions',
  'api.invalidKey': 'API key rejected by {service}: enter a new key in Settings → CLIs & extensions',
  'api.service': 'the service',
  'api.modelsTimeout': 'Timed out fetching the model list',
  'api.connectionTimeout': 'Connection test timed out',
  'api.connected': 'Connected to {url}',
  'api.networkHint': 'Cannot reach the service. Check your network and try again',
  'api.localHint': 'Check that the service is running and reachable',
  'api.noModel': 'No model selected: choose one in member settings or set defaultModel in extension settings',
  'api.runTimeout': 'API request timed out ({duration})',
  'api.stopped': 'Stopped',
  'api.cannotConnect': 'Cannot connect to {url}: {error}',
  'api.fileToolsFailed': 'Could not enable file tools: {error}',
  'api.tooManyTools': 'This batch exceeds the limit of {n} tool calls per turn. No calls were run; reduce the batch size',
  'api.toolRunning': '{name} running',
  'api.readToolsFallback': 'The request with tools was rejected ({error}); resent once without tools',
  'api.ephemeralDropped': '(File contents attached here were for that turn only and have been removed from memory.)',
  'api.readToolsUnavailable': '(The read_file tool is not available for this model this time. Do not call any tools; answer from the content of this prompt only.)',
  'api.toolRoundsExceeded': 'Stopped after {n} model tool call rounds to prevent an infinite loop',
  'api.imageFallback': 'This model rejected images ({error}); retrying with text only and omitting {n} images',
  'api.startOllama': 'Start Ollama first',
  'api.ollamaTestFailed': 'Could not test the Ollama connection',
  'api.ollamaConnectFailed': 'Could not connect to Ollama',
  'sys.error': 'Error: {message}',
  'sys.noAgents': 'No members are enabled. Add or enable a member in the sidebar first.',
  'sys.cwdFailed': 'Could not create the working directory {cwd}: {message}',
  'sys.stopped': 'Stopped.',
  'sys.stageFailed': 'Could not copy attachments into the working directory: {error}',
  'sys.unstageFailed': 'Could not remove the attachment staging folder ({dir}): {error}',
  'sys.agreed': 'Everyone agreed in round {round}.',
  'sys.askAnswered': 'Answering {name}: \n{answer}',
  'sys.askDeferred': "{name}'s question is yours to decide; carry on with your own judgement.",
  'sys.maxRoundsDivide': 'Reached the round limit ({max}). Moving on to dividing the work.',
  'sys.maxRoundsSummary': 'Reached the round limit ({max}). The lead will summarize.',
  'sys.unmatched': '**Some work could not be matched to a member** and was skipped:\n{list}',
  'sys.plan': (p) => `**Work plan**${p.summary ? `: ${p.summary}` : ''}\n\n${p.lines}`,
  'sys.planNoMatch': "None of the lead's assignments matched a member. Trying again.",
  'sys.planUnparsable': "Could not parse the lead's work plan. Trying again.",
  'sys.planLeadFailed': 'The lead "{name}" did not respond, so no work plan could be made. Check that member\'s setup (the status bar at the bottom left opens it).',
  'sys.planFailed': 'Dividing the work failed, so nothing was executed. Try the "Discussion only" mode, or pick a different lead.',
  'sys.nobodyAssigned': 'No member was assigned any work.',
  'sys.execFailed': '**Execution failed** for these members. Their work will not be reviewed:\n{list}',
  'sys.noReport': 'no report produced',
  'sys.noReviewer': 'No other member can act as reviewer (only one member is enabled). Skipping cross-review.',
  'sys.toolAudit': (p: Params) => `**File operations by ${p.name}**\n${p.list}`,
  'sys.toolUnknownError': 'unknown error',
  'sys.toolStatsApprox': ', approximate — check the actual file changes',
  'sys.reviewFailed': '**Cross-review failed.** These reviews produced no result, which does not mean the work is fine:\n{list}',
  'sys.reviewFailedItem': '- **{reviewer}** reviewing "{target}": {error}',
  'sys.noReviewText': 'no review produced',
  'sys.noSuccessfulReview': 'No review succeeded. Skipping the repair round.',
  'sys.noIssues': 'Cross-review found no issues. Skipping the repair round.',
  'sys.unresolved': '{names} cannot edit files. The review comments go straight into the summary.',
  'sys.fixFailed': '**Repair failed.** Review comments for these members remain unaddressed:\n{list}',
  'sys.retryBusy': 'A task is running. Wait for it to finish before retrying.',
  'sys.retryNotAllowed': 'This message cannot be retried (only the latest failed direct reply can be).',
  'sys.unfinishedOnSave': 'This message had not finished when it was saved',

  'transcript.new': '[New messages]',
  'transcript.sofar': '[Conversation so far]',
  'transcript.user': 'User',
  'transcript.system': 'System',
  'transcript.omitted': '…({n} messages in the middle omitted)…',
  'transcript.clipped': '\n…(this message was too long and has been truncated)…',

  'prompt.system.intro': 'You are an AI assistant named "{name}" taking part in a multi-AI roundtable with other AI assistants ({others}), moderated by the user.',
  'prompt.system.noOthers': '(no other members right now)',
  'prompt.system.persona': 'Your role and personality: {persona}',
  'prompt.system.noPersona': '(not set)',
  'prompt.system.rules': 'Rules:',
  'prompt.system.rule1': '- Reply in {lang}. Be concise and focused; do not repeat what others have already said.',
  'prompt.system.rule2': '- Respond concretely to the other members: agree, disagree (with reasons) or add to their points. When there is disagreement, state your own position clearly.',
  'prompt.system.rule3': '- Paragraphs starting with "[Name]:" are what other members or the user said. Do not prefix your own reply with a name; just write the content.',
  'prompt.system.agreed': '- During discussion, if you believe there is enough agreement to move on to dividing and executing the work, end your reply with {mark} on a line by itself. Do not write it before there is agreement. Only a line by itself counts; mentioning it inside a sentence is not agreement.',
  'prompt.system.ask': '- During discussion, if you hit a key decision only the user can make, you may end your reply with a question block: {open} on a line by itself, then the question on one line, then 2-4 possible answers as "- " bullets, and {close} on a line by itself. You may ask at most {max} times per discussion and only one question per round is accepted, so do not ask about minor things, and cover everything you can decide without an answer first.',
  'prompt.system.act': '- In the execution and review phases, actually do the work as instructed instead of only giving advice.',

  'prompt.task': '[Task]\n{task}\n',
  'prompt.discussLast': 'This is the final round of discussion. Converge and give your final position. If you agree to move on to dividing the work, end with {mark} on a line by itself.',
  'prompt.discuss': 'Share your view (round {round}/{max}). If you think the group can move on to dividing and executing the work, end with {mark} on a line by itself.',

  'prompt.directed': '[Direct reply] The user addressed you with @ in the latest message. Respond directly or carry out the request.',
  'prompt.directedOthers': '{others} were addressed at the same time. Handle your part; there is no need to wait for them.',
  'prompt.directedAlone': 'Only you were addressed this time. The other members will not speak.',
  'prompt.directedCanEdit': 'If needed, you can create and edit files and run commands directly in the working directory ({cwd}).',
  'prompt.directedReadOnly': 'You currently cannot edit files. When changes are needed, write out the full content or the steps.',

  'prompt.assign': '[Divide the work] You are the lead this time. Based on the discussion so far, break the task down and assign it to these members:',
  'prompt.rosterItem': '- {code} = "{name}" ({label}{readonly})',
  'prompt.rosterReadOnly': ', read-only, cannot edit files',
  'prompt.assignNoOverlap': 'Keep the files or modules each member owns from overlapping, so concurrent edits do not conflict. A member may be left without work.',
  'prompt.assignCodes': 'Fill the `agent` field with the codes above ({codes}), not names.',
  'prompt.assignJson': 'Output a single JSON object with no explanation or markdown fences, in this format:',
  'prompt.assignExample': '{"summary":"one sentence describing the overall approach","assignments":[{"agent":"A1","task":"a concrete, directly executable description of the work, including the files to create or change"}]}',
  'prompt.unmatchedItem': '- `{agent}`: {task}',
  'prompt.planItem': '- **{name}**: {task}',

  'prompt.execute': '[Execute] Below is the work assigned to you. Complete it now (working directory: {cwd}).',
  'prompt.executeCanEdit': 'You can create and edit files and run commands directly.',
  'prompt.executeReadOnly': 'Note: you currently cannot edit files. Write out the full code or the steps for what needs to be done.',
  'prompt.executeReport': 'When done, report briefly: what you did, which files you created or changed, and anything unfinished or needing someone else.',
  'prompt.failedItem': '- **{name}**: {error}',

  'prompt.review': '[Cross-review] Check the work "{name}" just completed. Open the relevant files and verify; do not rely on the report alone.',
  'prompt.reviewInline': '[Cross-review] Check the work "{name}" just completed. You cannot open files yourself, so the current contents of the changed files are included below. Verify against them, do not rely on the report alone, and do not draw conclusions about parts that are not shown.',
  'prompt.reviewReadTool': 'Files or parts that are not included below can be read with the read_file tool.',
  'prompt.reviewNoChanges': '[Cross-review] Check the work "{name}" just completed. No file changes were detected in the working directory this time (.git, node_modules and similar folders are not checked), so review it from the task and the report; if the task needed files in the working directory to change and they did not, point that out.',
  'prompt.reviewNoFilesChanged': 'No file changes were detected in the working directory this time (.git, node_modules and similar folders are not checked). If the task needed files in the working directory to change and they did not, point that out.',
  'prompt.reviewAttached': '[Cross-review] Check the work "{name}" just completed. The current contents of the changed files are included below; verify against them and do not rely on the report alone.',
  'prompt.reviewUntouched': '[Cross-review] Check the work "{name}" just completed. According to its file tool records, "{name}" changed no files this time; review it from the task and the report, and if the task needed file changes that were not made, point that out.',
  'prompt.reviewUntouchedLine': 'According to its file tool records, "{name}" changed no files this time. If the task needed file changes that were not made, point that out.',
  'prompt.reviewReadOnly': '[Cross-review] Check the work "{name}" just completed. "{name}" had no permission to change files this time, so its work does not change files; review it from the task and the report.',
  'prompt.reviewFilesAll': 'Files changed in this task by all executing members (not necessarily by "{name}"; compare with its task and report):\n{list}',
  'prompt.reviewReadToolAny': 'You can read files in the working directory with the read_file tool to check the report.',
  'prompt.reviewReadToolUnlisted': 'You can read files in the working directory with the read_file tool. The changed files could not be determined this time, so read the files mentioned in the task and the report yourself before you decide; if you cannot read them, say what you could not verify and do not write {mark}.',
  'prompt.reviewInlineUnknown': '[Cross-review] Check the work "{name}" just completed. You cannot open files yourself, and the changed file contents could not be obtained this time, so you cannot see the actual changes. Do not judge the work fine from the report alone: say what you could not verify, and do not write {mark}.',
  'prompt.reviewWhat': 'Point out: clear mistakes, anything inconsistent with the discussion, and possible improvements. Be concise.',
  'prompt.reviewFiles': 'Files changed in this task:\n{list}',
  'prompt.reviewContent': 'Current contents of the changed files:',
  'prompt.reviewFileBlock': '----- {path} -----\n{content}',
  'prompt.reviewFileUnreadable': '----- {path} -----\n(could not read: {error})',
  'prompt.reviewOmitted': 'The following changed files exceeded the number or size limit for attached content and are not included:\n{list}\nDo not draw conclusions about them, and say in your reply what you could not verify as a result.',
  'prompt.reviewTruncated': '\n…(file too long, the rest is omitted)…',
  'prompt.reviewMark': 'If you confirm there are no issues at all, end your reply with {mark} on a line by itself. Leave it out if anything needs fixing.',
  'prompt.reviewTask': 'Their assigned work:\n{task}',
  'prompt.reviewReport': 'Their report:\n{report}',
  'prompt.reviewNote': '[{reviewer}]:\n{text}',

  'prompt.fix': '[Repair] Below are review comments from other members on your work. Handle them now: fix what you can directly in the files, and give a clear reason for anything you choose not to fix.',
  'prompt.fixLast': 'This is the final round of changes; there will be no further review. Report briefly what you changed, what you did not, and why.',
  'prompt.fixTask': 'Your assigned work:\n{task}',
  'prompt.fixNotes': 'Review comments:\n{notes}',
  'prompt.fixFailedItem': '- **{name}**: {error}',

  'prompt.summary.failed': 'Execution failed for these members and their work was not reviewed. State this clearly in the summary:\n{list}',
  'prompt.summary.failedItem': '- {name}: {error}',
  'prompt.summary.reviewFailed': 'These cross-reviews did not complete, so the corresponding work was effectively unchecked. Mark it as "not reviewed" in the summary; do not describe it as problem-free:\n{list}',
  'prompt.summary.reviewFailedItem': '- {reviewer} reviewing {target}: {error}',
  'prompt.summary.fixFailed': 'The repair round failed for these members, so the issues the reviews raised still exist. List them as unresolved in the summary:\n{list}',
  'prompt.summary.fixFailedItem': '- {name}: {error}\n  Unaddressed review comments:\n{notes}',
  'prompt.summary.unresolved': 'These members cannot edit files, so their review comments are still unaddressed. List them in the summary and say what the user needs to do:\n{list}',
  'prompt.summary.unresolvedItem': '- {name}:\n{notes}',
  'prompt.summary.git': 'At the end of execution the git changes in the working directory were as follows. This is the **current state of the working tree** and may include changes that existed before this task started. Report it as is; do not claim all of these changes came from this task:\n{changes}',
  'prompt.summary.divide': '[Summary] As the lead, briefly summarize based on the execution reports, cross-reviews and repairs: what was completed, what the reviews found and fixed, and what remains unresolved or needs a decision from the user.',
  'prompt.summary.discuss': '[Summary] As the lead, briefly summarize the conclusions of this discussion, the points of disagreement, and the recommended next steps.',
  'git.more': '- ({n} more changed files not listed)',
  'git.preexisting': ' (already modified before execution)',

  'attach.header': (p) => `[Attachments] The user provided ${p.n} ${Number(p.n) === 1 ? 'attachment' : 'attachments'}:`,
  'attach.path': '- {label}\n  Path: {path}',
  'attach.imageInline': '- {label} (image attached to this message)',
  'attach.textInline': '- {label} (content below)',
  'attach.inlineCap': '- {label} (inline text limit reached, content omitted)',
  'attach.truncated': '\n…(file too long or attachment limit reached; truncated. See the original file for the full content)…',
  'attach.unreadable': 'Note: you cannot read the content of {names}. Do not guess from the file names; say so in your reply if needed.',

  'export.title': '# AI Roundtable conversation',
  'export.user': 'User',
  'export.agent': 'AI member',
  'export.system': 'System',
  'export.systemError': 'System error',
  'export.systemWarn': 'System warning',
  'export.timeUnknown': 'unknown time',
  'export.rawUsage': '> Raw usage: {fields}',
  'export.noFields': 'no fields',
  'export.usage': '> Usage: {fields}',
  'export.input': 'input: {n}',
  'export.cached': '{n} cached',
  'export.cacheWrite': '{n} cache write',
  'export.cachedInput': 'cached input: {n}',
  'export.output': 'output: {n}',
  'export.cost': 'cost: ${n}',
  'export.attachments': '> Attachments: {list}',
  'export.unreviewed': '> ⚠ Not reviewed: no other member checked this change — verify the diff yourself.',
  'export.error': '> Error: {text}',
  'export.empty': '_(no text)_',
  'phase.idle': 'Idle', 'phase.direct': 'Direct', 'phase.discuss': 'Discuss', 'phase.divide': 'Divide',
  'phase.execute': 'Execute', 'phase.review': 'Review', 'phase.repair': 'Repair', 'phase.summary': 'Summary',

  'main.extNotFound': 'This API extension was not found. Save its settings first',
  'main.extNoTest': 'This extension does not support an API connection test',
  'main.nothingToExport': 'There is no conversation to export',
  'main.exportTitle': 'Export this conversation',
  'main.stillRunning': 'A task is still running. Stop it before loading a saved conversation',
  'main.attachFilter': 'Supported attachments',
  'adapter.missing': 'CLI "{cli}" not found: its extension may have been deleted or failed to load. Check Settings → CLIs & extensions',
  'adapter.failed': '{label} failed: {message}',
  // ---------- CLI member runtime messages ----------
  'proc.seconds': (p: Params) => `${p.n} second${Number(p.n) === 1 ? '' : 's'}`,
  'proc.minutes': (p: Params) => `${p.n} minute${Number(p.n) === 1 ? '' : 's'}`,
  'proc.minutesSeconds': '{m} min {s} s',
  'proc.timeout': 'Timed out ({time})',
  'proc.timeoutSigterm': 'Timed out ({time}); sent SIGTERM.',
  'proc.timeoutSigkill': 'The process was still running after the timeout; sent SIGKILL.',
  'proc.notFound': 'Command not found: {bin}',
  'proc.checkTimeout': 'timed out',
  'proc.checkSkipped': '(check skipped)',
  'cli.spawnFailed': 'Could not start {bin}: {detail}',
  'cli.timedOut': '{bin} timed out',
  'cli.exitCode': '{bin} exited with code {code}',
  'cli.failed': '{name} failed',
  'cli.reportedError': '{name} reported an error',
  'cli.turnFailed': 'The {name} turn failed',
  'cli.customNotSet': 'No custom command has been set',
  'cli.customCommand': 'the command',
  'cli.unparsableJson': 'Could not parse the JSON output: {detail}',
  'cli.loginHint': 'Installed, but not logged in. Open Terminal, run {cmd} and follow the prompts.',
  'cli.notLoggedIn': '{name} is not logged in, or the login has expired. Open Terminal, run {cmd}, follow the prompts, then try again.',
  'act.run': 'Run command: {detail}',
  'act.read': 'Read file: {detail}',
  'act.edit': 'Edit file: {detail}',
  'act.write': 'Write file: {detail}',
  'act.delete': 'Delete file: {detail}',
  'act.glob': 'Find files: {detail}',
  'act.grep': 'Search contents: {detail}',
  'act.ls': 'List folder: {detail}',
  'act.tool': 'Tool: {detail}',
  'act.changes': 'Edit files ({n})',
  'act.webSearch': 'Web search: {detail}',
  'cursor.effortIgnored': 'Cursor encodes effort in the model name, so {effort} was ignored',
  // ---------- Attachment rejection reasons (shown as "Could not attach the file: …") ----------
  'attachErr.notFormat': 'The content is not {fmt} (the extension does not match the actual content)',
  'attachErr.looksLike': 'The content looks like {kind}, not a text file',
  'attachErr.nul': 'Text files cannot contain NUL bytes (the content looks binary)',
  'attachErr.utf8': 'Text files must be valid UTF-8',
  'attachErr.json': 'The content is not valid JSON (the extension does not match the actual content)',
  'attachErr.tooBig': 'Over the {limit} per-file limit (this file is {size})',
  'attachErr.totalTooBig': 'Over the {limit} combined limit for one message',
  'attachErr.tooMany': 'At most {n} files at a time',
  'attachErr.unsupported': 'Unsupported file type "{ext}". Accepted types: {list}',
  'attachErr.noExt': 'no extension',
  'attachErr.empty': 'The file is empty',
  'attachErr.notFile': 'Not a regular file',
  'attachErr.unrecognized': 'The attachment content format was not recognised',
  'attachErr.noSource': 'No file content or path was given',
  'attachErr.badConversation': 'Invalid conversation ID',
  'attachErr.unsafeName': 'Could not create a safe storage name',
  'attachErr.exists': 'The attachment storage path already exists',
  'attachErr.unknownSize': 'unknown size',
  'attachErr.listSep': ', ',
  'bin.elf': 'an ELF executable',
  'bin.macho': 'a Mach-O executable',
  'bin.machoFat': 'a Mach-O universal binary',
  'bin.windows': 'a Windows executable',
  'bin.zip': 'a ZIP / Office archive',
  'bin.gzip': 'a gzip archive',
  // ---------- Conversation history ----------
  'session.notTranscript': 'This is not a conversation record',
  'session.noMessages': 'This is not a conversation record: the messages array is missing',
  'session.badId': 'Invalid record ID',
  'session.missing': 'This record no longer exists (it may have been deleted)',
  // ---------- Extension loading, saving and Ollama quick setup ----------
  'ext.duplicateId': 'id "{id}" is already used by {file}',
  'ext.badJson': 'Invalid JSON: {error}',
  'ext.badJsonUnsaved': 'Invalid JSON, not saved: {error}',
  'ext.badType': 'type must be "cli" or "openai" (write a .js plugin if you need more flexibility)',
  'ext.noRun': 'Must export a run(agent, ctx, kit) function',
  'ext.badFileName': 'File names may only contain letters, digits, . _ - and must end in .json or .js',
  'ext.badTemplate': 'Invalid template name',
  'ext.exists': 'An extension named {file} already exists',
  'ext.noUserDir': 'The extensions folder was not found',
  'ext.noTemplateDir': 'The built-in Ollama template folder was not found',
  'ext.ollamaTemplateUnreadable': 'Could not read the Ollama template: {error}',
  'ext.ollamaConfigUnreadable': 'Could not read the existing Ollama settings: {error}',
  'ext.ollamaModelMissing': 'Ollama does not have the model "{model}". Download it first and try again',
  // 只會嵌在 ext.legacyKeyFailed 的句子中間,所以小寫開頭
  'ext.noKeychain': 'the system keychain is unavailable',
  'ext.legacyKeyFailed': 'Found a legacy plain-text API key, but {error}. Set an environment variable and remove apiKey from the file',
  'ext.legacyKeyMigrated': 'Moved the legacy plain-text API key into the system keychain.',
  // ---------- Extension config validation errors ----------
  'spec.contentObject': 'The content must be an object',
  'spec.badId': 'id must be 1–64 letters, digits, . _ or -, starting with a letter or digit',
  'spec.modelsShape': 'models must be an array or "auto"',
  'spec.usageShape': 'usageShape must be {list}; leave it out to detect it from the fields',
  'spec.binShape': 'bin must be a command name or path',
  'spec.baseUrl': 'baseUrl must be a URL starting with http:// or https://',
  'spec.apiKeyEnv': 'apiKeyEnv must be an environment variable name',
  'spec.plainApiKey': 'The plain-text apiKey field is no longer supported; move the key into the API key field in the extension settings',
  'spec.mustBeObject': '{field} must be an object',
  'spec.mustBeArray': '{field} must be an array',
  'spec.mustBeString': '{field} must be a string',
  'spec.mustBeBoolean': '{field} must be a boolean',
  'spec.mustBePositive': '{field} must be a positive number',
  'spec.mustBePositiveInt': '{field} must be a positive integer',
  'spec.mustBeOneOf': '{field} must be {list}',
  'spec.onlyAccepts': '{field} only accepts {list}',
  'spec.noDuplicates': '{field} must not contain duplicates',
  'spec.badFormat': '{field} has an invalid format',
  'spec.badRegex': '{field} is not a valid regular expression: {error}',
  'spec.requiresTogether': '{b}=true must also be set explicitly when {a}=true',
  'spec.listSep': ', ',
  'spec.or': ' or ',
};

const DICTS: Record<TextLocale, Record<string, Entry>> = { 'zh-Hant': ZH, en: EN };

export function tx(locale: TextLocale, key: string, params: Params = {}): string {
  const entry = DICTS[locale][key] ?? ZH[key];
  if (entry == null) return key;
  const text = typeof entry === 'function' ? entry(params) : entry;
  return text.replace(/\{(\w+)\}/g, (m, name: string) => (name in params ? String(params[name]) : m));
}

// 名稱清單的分隔符:中文用頓號,英文用逗號
export function joinNames(locale: TextLocale, names: readonly string[]): string {
  return names.join(locale === 'en' ? ', ' : '、');
}

// 中文用全形引號包名稱,英文用雙引號
export function quoteName(locale: TextLocale, name: string): string {
  return locale === 'en' ? `"${name}"` : `「${name}」`;
}
