// 主程序端的文案:orchestrator 的系統訊息、給成員的提示詞、附件提示、匯出的 Markdown。
// 介面文案在 renderer/i18n.ts;這裡只放 renderer 看不到、由主程序組出的字串。
// 繁體中文是原始文案,英文是對應翻譯。AGREED / NO_ISSUES 這類標記是協定,不翻譯。

export type TextLocale = 'zh-Hant' | 'en';
type Params = Record<string, string | number>;
type Entry = string | ((p: Params) => string);

// 作業系統語系。Electron 主程序的 Intl 預設是 en-US、不看系統語言,所以 main.ts 啟動時
// 用 app.getLocale() 設定這個值;測試環境沒有 Electron,退回 Intl。
let systemLocaleTag = '';
export function setSystemLocale(tag: string): void { systemLocaleTag = tag || ''; }

// 設定值 'system'(或沒設定)時跟著作業系統
export function resolveTextLocale(setting: string | null | undefined): TextLocale {
  if (setting === 'zh-Hant' || setting === 'en') return setting;
  let system = systemLocaleTag;
  if (!system) { try { system = Intl.DateTimeFormat().resolvedOptions().locale || ''; } catch {} }
  return system.toLowerCase().startsWith('zh') ? 'zh-Hant' : 'en';
}

const ZH: Record<string, Entry> = {
  'api.missingKeyEnv': '缺少 API key:請到「設定 → CLI 與擴充」填入,或設定環境變數 {env}',
  'api.missingKey': '缺少 API key:請到「設定 → CLI 與擴充」填入並儲存',
  'api.invalidKey': 'API key 被 {service} 拒絕:請到「設定 → CLI 與擴充」重新填入',
  'api.service': '服務',
  'api.modelsTimeout': '取得模型清單逾時',
  'api.connectionTimeout': '測試連線逾時',
  'api.connected': '已連線 {url}',
  'api.networkHint': '連不上服務:請確認網路,或稍後再試',
  'api.localHint': '請確認服務已啟動並可連線',
  'api.noModel': '沒有指定模型:請在成員設定選擇模型,或在擴充設定填 defaultModel',
  'api.runTimeout': 'API 執行逾時({duration})',
  'api.stopped': '已停止',
  'api.cannotConnect': '無法連線到 {url}:{error}',
  'api.fileToolsFailed': '無法啟用檔案工具:{error}',
  'api.tooManyTools': '這批工具呼叫會超過每回合 {n} 次上限，整批未執行；請減少呼叫數',
  'api.toolRunning': '{name} 執行中',
  'api.readToolsFallback': '帶工具的請求被拒絕({error}),改成不帶工具重送一次',
  'api.ephemeralDropped': '(這裡原本附上的檔案內容只用於那一回合,已從記憶中移除)',
  'api.readDropped': '(已讀取 {n} 字元;內容已從記憶中移除,需要時請重新讀取)',
  'ext.timeoutHint': '如果這個模型需要更久,可以在「設定 → CLI 與擴充」編輯這個擴充,調高「每回合逾時上限」。',
  'api.toolTruncated': '…(已截短)',
  'api.imagesDropped': '(先前回合附上的 {n} 張圖片已從記憶中移除)',
  'api.readToolsUnavailable': '(這個模型這次無法使用 read_file 工具。請不要呼叫任何工具,只依上面提示詞裡的內容作答。)',
  // 檔案工具:工具說明、錯誤訊息與紀錄摘要。模型會讀,工具紀錄裡使用者也看得到
  'ft.def.read': '讀取工作目錄內的 UTF-8 文字檔。修改既有檔案前必須先呼叫，並把 sha256 傳給寫入工具。',
  'ft.def.path': '相對於工作目錄的路徑',
  'ft.def.offset': '從第幾個字元開始，預設 0',
  'ft.def.limit': '最多回傳字元數,預設 65536。超過 65536 會夾到上限;內容未完整回傳時 truncated=true',
  'ft.def.write': '建立小型文字檔，或在 sha256 未改變時整檔覆寫。既有檔案必須提供 expectedSha256；新檔必須 createOnly=true。',
  'ft.def.content': '完整 UTF-8 文字內容，上限 256KB',
  'ft.def.createOnly': '建立新檔時必須為 true；檔案已存在就失敗',
  'ft.def.reason': '本次修改目的，會進入審查紀錄',
  'ft.def.replace': '以精確文字做局部替換。預設要求 oldText 只出現一次；多處替換必須明確指定 replaceAll=true。',
  'ft.def.oldText': '至少 24 個字元的精確原文',
  'ft.def.newText': '替換後文字',
  'ft.def.replaceAll': '明確允許替換全部匹配；預設 false',
  'ft.autoExecDir': '不可寫入 {dir} 底下的檔案:這裡的內容會被自動執行',
  'ft.autoExecFile': '不可寫入 {file}:這個檔案會被自動執行',
  'ft.executable': '不可寫入 {file}:這個檔案帶有執行權限',
  'ft.vcs': '不可讀取或修改版本控制內部檔案（.git、.hg、.svn）',
  'ft.pathEmpty': 'path 必須是非空白相對路徑',
  'ft.pathAbsolute': 'path 必須是相對於工作目錄的路徑',
  'ft.pathNul': 'path 不可包含 NUL',
  'ft.textNul': '只允許 UTF-8 文字檔，不可包含 NUL',
  'ft.textInvalid': '只允許有效的 UTF-8 文字檔',
  'ft.contentString': 'content 必須是字串',
  'ft.contentUtf8': 'content 必須是有效的 UTF-8 文字',
  'ft.contentNul': 'content 不可包含 NUL',
  'ft.contentTooBig': '檔案內容超過 {max} bytes 上限',
  'ft.notRegular': '只允許一般檔案',
  'ft.fileTooBig': '檔案超過 {max} bytes 上限',
  'ft.noWorkdir': '工作目錄不存在',
  'ft.workdirNotDir': '工作目錄不是資料夾',
  'ft.outside': '路徑超出工作目錄',
  'ft.symlinkWrite': '不允許透過符號連結寫入',
  'ft.symlinkOutside': '符號連結指向工作目錄外',
  'ft.noParent': '新檔案的父資料夾不存在',
  'ft.outputFull': '本回合工具輸出已達上限',
  'ft.tooManyCalls': '本回合工具呼叫不可超過 {n} 次',
  'ft.argsTooBig': '工具參數超過 {max} 字元上限',
  'ft.outputReserve': '本回合工具輸出額度不足，未修改檔案',
  'ft.argsJson': '工具參數不是有效 JSON',
  'ft.argsObject': '工具參數必須是物件',
  'ft.readOnly': '這個回合只能讀取檔案,不能修改',
  'ft.lockedTest': '`{path}` 是任務開始前就存在的測試檔,修復回合不可以修改它。要讓測試通過請改實作;測試本身有問題就在回報裡說明,不要動它',
  'ft.unknownTool': '不支援的工具:{name}',
  'ft.offset': 'offset 必須是非負整數',
  'ft.limit': 'limit 必須是至少 1 的整數(超過 {max} 會自動夾到上限,不會失敗)',
  'ft.reason': 'reason 必須是 1–500 字元',
  'ft.createExists': 'createOnly=true，但檔案已存在',
  'ft.createNeedsFlag': '建立新檔案必須指定 createOnly=true',
  'ft.createNoSha': '建立新檔案不可提供 expectedSha256',
  'ft.overwriteNeedsSha': '覆寫既有檔案前必須提供 read_file 回傳的 expectedSha256',
  'ft.shaMismatch': '檔案已被其他成員修改，sha256 不符；請重新 read_file',
  'ft.changedBeforeWrite': '寫入前檔案又被修改，請重新 read_file',
  'ft.oldTextShort': 'oldText 至少需要 {n} 個非空白文字字元',
  'ft.newTextString': 'newText 必須是字串',
  'ft.replaceUtf8': '替換文字必須是有效且不含 NUL 的 UTF-8',
  'ft.controlChars': '替換文字不可包含控制字元(tab、換行、歸位除外)',
  'ft.replaceNeedsSha': 'replace_text 必須提供 read_file 回傳的 expectedSha256',
  'ft.notFound': '找不到 oldText，未修改檔案',
  'ft.multiple': 'oldText 出現 {n} 次；請提供更長的唯一內容，或明確設定 replaceAll=true',
  'ft.summaryOk': '{name} {path} 完成{counts}',
  'ft.summaryFail': '{name} {path} 失敗:{error}',
  'ft.unknownError': '未知錯誤',
  'api.toolRoundsExceeded': '模型工具呼叫往返超過 {n} 次，已停止以避免無限循環',
  'api.toolNoProgress': '連續 {n} 輪的工具呼叫全部失敗，已停止:再試下去只會重複同一個錯誤',
  'api.imageFallback': '此模型不接受圖片({error}),已略過 {n} 張圖片改用純文字重送',
  'api.startOllama': '請先啟動 Ollama',
  'api.ollamaTestFailed': '無法測試 Ollama 連線',
  'api.ollamaConnectFailed': '無法連線到 Ollama',
  // ---------- 系統訊息 ----------
  'sys.error': '發生錯誤:{message}',
  'sys.noAgents': '沒有啟用的成員,請先在左側新增或啟用成員。',
  'sys.cwdFailed': '無法建立工作目錄 {cwd}:{message}',
  'sys.stopped': '已停止。',
  'sys.stageFailed': '附件無法複製到工作目錄:{error}',
  'sys.unstageFailed': '無法清除工作目錄的附件暫存({dir}):{error}',
  'sys.agreed': '第 {round} 回合全員達成共識。',
  'sys.askAnswered': '回答 {name} 的提問:\n{answer}',
  'sys.askDeferred': '{name} 的提問由你們自行決定,請依你們的判斷繼續。',
  'sys.maxRoundsDivide': '已達最大討論回合({max}),直接進入分工。',
  'sys.maxRoundsSummary': '已達最大討論回合({max}),由主持人總結。',
  'sys.unmatched': '**有工作無法對應到成員**,已跳過:\n{list}',
  'sys.plan': (p) => `**分工結果**${p.summary ? `:${p.summary}` : ''}\n\n${p.lines}`,
  'sys.taskSummary.title': '**任務結果** · 用時 {duration}',
  'sys.taskSummary.member': '- {name}:{outcome}{reviewers}',
  'sys.taskSummary.reviewedBy': '({names} 審查)',
  'sys.taskSummary.files': '改動 {n} 個檔案:',
  'sys.taskSummary.file': '- {path} +{added} −{removed}',
  'sys.taskSummary.noFiles': '這次任務沒有改動檔案。',
  'sys.taskSummary.usage': '輸入 {input} / 輸出 {output} token',
  'sys.taskSummary.verify.passed': '已執行的檢查通過(含專案驗證指令)',
  'sys.taskSummary.verify.syntax-only': '僅語法檢查通過,不是可合併',
  'sys.taskSummary.evidence': '驗證紀錄:已檢查 {n} 個 JS / JSON 檔案的語法',
    'sys.taskSummary.freshness.current': '檢查時工作目錄指紋一致(不含相依套件、快取與版本控制目錄)。',
    'sys.taskSummary.freshness.stale': '檔案版本已變動,這份驗證證據需要重驗。',
    'sys.taskSummary.freshness.unknown': '尚未確認證據是否對應目前檔案版本。',
    'sys.taskSummary.previousVerification': '先前的驗證紀錄:',
    'sys.taskSummary.reviewStale': '檔案版本變動後尚未重新審查,原審查結論僅供參考。',
    'sys.reverifyBusy': '驗證或還原進行中,請等結束後再操作。',
    'sys.reverifyUnavailable': '無法重驗:任務、工作目錄或設定已改變,或操作已停止。',
    'phase.verify': '重新驗證',
  'sys.taskSummary.checkedAt': '檢查時間: {time}。後續改檔尚未驗證。',
  'sys.taskSummary.noCommands': '未執行專案驗證指令',
  'sys.taskSummary.unknownScope': '無法確認改動範圍',
  'sys.taskSummary.check.passed': '通過',
  'sys.taskSummary.check.failed': '失敗',
  'sys.taskSummary.check.timeout': '逾時',
  'sys.taskSummary.check.unavailable': '無法執行檢查',
  'sys.taskSummary.check.unsupported': '內建語法檢查不支援此格式',
  'sys.taskSummary.check.limit': '超過語法檢查上限',
  'sys.taskSummary.check.skipped': '前一道失敗,未執行',
  'sys.taskSummary.verify.failed': '自動驗證沒過',
  'sys.taskSummary.verify.none': '沒有自動驗證',
  'sys.taskSummary.repairBroke': '⚠ 修復回合反而把東西改壞了:執行階段原本通過的檢查,修復之後變成不通過。',
  'sys.taskSummary.rollbackRepair': '已自動收回修復回合,保留執行階段的改動。上方驗證為回退後的結果;需求仍未完成。',
  'sys.taskSummary.rollbackTask': '已自動還原到任務開始前。上方驗證為回退後的結果;需求仍未完成。',
  'sys.taskSummary.rollbackPartial': '自動回退未完成,仍有檔案無法還原。請查看回退紀錄並確認工作目錄。',
  'sys.taskSummary.rollbackUnavailable': '沒有可用的基準點,未自動回退。請確認工作目錄中的檔案。',
  'sys.taskSummary.testsTouched': '動到既有測試',
  'sys.taskOutcome.approved': '✓ 審查通過',
  'sys.taskOutcome.repaired': '已依審查意見修復(未再審查)',
  'sys.taskOutcome.unresolved': '⚠ 有未解決的問題',
  'sys.taskOutcome.unreviewed': '尚未審查',
  'sys.taskOutcome.failed': '✗ 執行失敗',
  'sys.planNoMatch': '主持人的分工沒有任何一項能對應到成員,再試一次。',
  'sys.planUnparsable': '主持人輸出的分工格式無法解析,再試一次。',
  // 主持人整個回合就失敗時(CLI 沒安裝、key 失效、逾時),說「格式無法解析」會把使用者
  // 指向錯的地方:要修的是主持人這位成員,不是它的輸出格式。
  'sys.planLeadFailed': '主持人「{name}」沒有回應,無法產生分工。請檢查這位成員的設定(左下角的狀態列可以直接開啟)。',
  'sys.planFailed': '分工失敗,已中止分工與執行。可以改用「只討論」模式,或換一位主持人再試一次。',
  'sys.nobodyAssigned': '沒有任何成員被分配到工作。',
  'verify.syntaxFailed': '**自動語法檢查沒過**,這些檔案現在載不起來:\n{list}',
  'verify.syntaxItem': '- `{file}`:{error}',
  'verify.commandFailed': '**驗證指令失敗**:`{command}`(結束代碼 {code}),輸出:\n```\n{output}\n```',
  'verify.commandTimeout': '**驗證指令逾時**:`{command}`,輸出:\n```\n{output}\n```',
  'verify.commandNotFound': '**找不到「設定 → 一般 → 驗證指令」裡的這道指令**:`{command}`,所以這次沒有真的驗證過。輸出:\n```\n{output}\n```',
  'verify.gatesPassed': '在它之前這幾道都通過了:{list}',
  'verify.noOutput': '(沒有輸出)',
  'sys.testsTouched': '**這次改動動到任務開始前就有的測試檔**:\n{list}\n讓測試通過應該改實作,不是改測試。請確認這些改動是必要的。',
  'sys.testsLockedFixed': '修復回合改到既有的測試檔:\n{list}',
  'prompt.reviewConflict': '注意:這幾個檔案被多位成員同時改到({list})。若這次有隔離目錄,重疊的檔案沒有合併回工作目錄,各自版本留在隔離目錄;若沒有隔離,後寫的會蓋掉先寫的。請確認工作目錄裡的內容是否完整。',
  'prompt.reviewTests': '注意:這次改動動到了任務開始前就存在的測試檔({list})。請特別確認這些測試不是為了讓結果變綠而被放寬、刪減或改掉期望值;測試被改軟的話,「測試通過」就不算數。',
  'prompt.fixTestLock': '修復時不可以修改任務開始前就存在的測試檔({list})。要讓測試通過請改實作;如果你認為測試本身有錯,在回報裡說明理由,不要動它。',
  'sys.autoRevertedFix': '修復回合退步,已先收回修復回合的改動:還原 {restored} 個檔案、刪除 {deleted} 個新增的檔案。執行階段的成果保留著,接著重新驗證。',
  'sys.autoReverted': '自動檢查沒過,已先把工作目錄還原到任務開始前:回寫 {restored} 個檔案、刪除 {deleted} 個。接著重新驗證,任務仍未完成。',
  'sys.autoRevertPartly': '自動檢查沒過,已試著把退步的改動還原(回寫 {restored} 個檔案、刪除 {deleted} 個),但這些檔案還原不了,請自行確認:\n{list}',
  'sys.autoRevertUnavailable': '自動檢查沒過,但沒有可用的回退基準點,未自動還原。請確認工作目錄中的檔案。',
  'sys.rollbackUnresolved': '最終檢查失敗或修復後退步,app 已啟動自動回退。成果仍未交付,回退不代表需求已完成;回退結果與後續驗證另列。',
  'sys.revertedFix': '已收回修復回合的改動:還原 {restored} 個檔案、刪除 {deleted} 個新增的檔案。執行階段的成果保留著。',
  'sys.reverted': '已還原這次任務的改動:回寫 {restored} 個檔案、刪除 {deleted} 個。工作目錄回到任務開始前的樣子。',
  'sys.revertPartly': '已還原大部分改動(回寫 {restored} 個檔案、刪除 {deleted} 個),但這些檔案還原不了,請自行確認:\n{list}',
  'sys.projectRules': '已套用工作目錄的專案規則:`{file}`{truncated}',
  'sys.projectRulesTruncated': '(太長,只取前面一段)',
  'sys.parallelConflict': '**有檔案被多位成員同時改到**。重疊的檔案沒有合併回工作目錄,各自的版本留在隔離目錄:\n{list}',
  'sys.parallelConflictItem': '- `{file}`:{names}',
  'sys.lanesReady': '平行執行使用各自的隔離目錄,結束後再合併沒有重疊的改動。',
  'sys.lanesUnavailable': '無法準備隔離目錄({error}),這次改在原工作目錄依序執行,不會同時寫檔。',
  'sys.lanesKept': '尚有未合併的改動,隔離目錄保留在 `{dir}`。請先取回需要的版本,再自行清理。',
  'sys.sharedConflict': '**多位成員改過相同檔案**,後一次寫入可能覆蓋前一次的內容:\n{list}',
  'sys.mergeFailed': '這些改動無法安全合併,未採用的版本保留在隔離目錄: {list}',
  'sys.mergeUnresolved': '尚有隔離目錄中的改動未合併,成果仍未交付。請人工處理,不能只憑審查通過當成完成。',
  'sys.repairHandoff': '{repairer} 已指出 {author} 成果的問題,這次由 {repairer} 直接修復,再交給 {reviewer} 獨立複查。',
  'prompt.repairHandoff': '你正在接手修復 {name} 的成果。請先讀目前工作目錄中的檔案,直接處理你指出的問題,不要只回傳修改建議。',
  'prompt.repairedBy': '這次修復由 {name} 接手完成,請獨立確認實際改動,不要只採信修復報告。',
  'prompt.executeLane': '請只修改這個隔離目錄。結束後 app 會把沒有和其他成員重疊的改動合併回工作目錄。',
  'sys.testsWritten': '已寫好測試,實作回合不能修改它們:\n{list}',
  'sys.testsNone': '這一回合沒有寫出任何測試檔,實作回合就沒有測試可以遵循。',
  'sys.verifyOk': '自動驗證通過。',
  'sys.verifyFailed': '自動驗證沒過:\n{notes}',
  'sys.verifyNone': '沒有可以自動驗證的東西(沒有改到 .js/.json,也沒有設定驗證指令)。',
  'prompt.reviewVerify': '這是 app 自己跑出來的結果,不是任何成員說的:\n{notes}\n請把這些當成必須處理的問題。',
  'prompt.reviewVerifyOk': '這些改動已經通過 app 的自動驗證(改動檔案可以載入{command})。',
  'prompt.reviewVerifyCommand': ',驗證指令也執行成功',
  'prompt.fixVerify': '自動驗證的結果(app 實際執行的,不是誰的意見):\n{notes}',
  'sys.execFailed': '**執行失敗**,這些成員的成果不會進入審查:\n{list}',
  'sys.execSalvaged': '**執行回合中途失敗**,但已經改了檔案,照樣送交審查,確認留下來的檔案能不能用:\n{list}',
  'sys.rereviewIssues': '複查後「{names}」仍有問題,已帶入總結。',
  'sys.noReport': '沒有產生回報',
  'sys.noReviewer': '找不到可以擔任審查者的其他成員(整場只有一名啟用成員),略過交叉審查。',
  'sys.toolAudit': (p: Params) => `**${p.name} 的檔案操作**\n${p.list}`,
  'sys.toolUnknownError': '未知錯誤',
  'sys.toolStatsApprox': ',為近似值,請以實際檔案改動為準',
  'sys.reviewFailed': '**交叉審查失敗**,這些審查沒有結果,不代表被審查的成果沒有問題:\n{list}',
  'sys.reviewFailedItem': '- **{reviewer}** 審查「{target}」:{error}',
  'sys.noReviewText': '沒有產生審查意見',
  'sys.noSuccessfulReview': '沒有任何成功的審查意見,略過修復回合。',
  'sys.noIssues': '交叉審查沒有發現問題,略過修復回合。',
  'sys.unresolved': '「{names}」沒有修改檔案的權限,審查意見將直接帶入總結。',
  'sys.fixFailed': '**修復失敗**,以下成員的審查意見仍未處理:\n{list}',
  'sys.retryBusy': '目前有任務進行中,請等它結束再重試。',
  'sys.retryNotAllowed': '這則訊息無法重試(只有最近一次失敗的指定回覆可以重試)。',
  'sys.unfinishedOnSave': '這則訊息在儲存時尚未完成',

  // ---------- 對話紀錄 ----------
  'transcript.new': '【新訊息】',
  'transcript.sofar': '【目前為止的對話紀錄】',
  'transcript.user': '使用者',
  'transcript.system': '系統',
  'transcript.omitted': '…(已省略中間 {n} 則訊息)…',
  'transcript.clipped': '\n…(此則訊息過長,已截斷)…',

  // ---------- 提示詞 ----------
  'prompt.system.intro': '你是名為「{name}」的 AI 助理,正在一個多 AI 圓桌會議中與其他 AI 助理({others})協作,由使用者主持。',
  'prompt.system.noOthers': '(目前沒有其他成員)',
  'prompt.system.persona': '你的角色與個性:{persona}',
  'prompt.system.noPersona': '(未設定)',
  'prompt.system.rules': '規則:',
  'prompt.system.rule1': '- 使用{lang}回覆,簡潔、有重點,不要重複別人已經說過的內容。',
  'prompt.system.rule2': '- 對其他成員的看法要具體回應:同意、反對(附理由)或補充。有分歧時要明確說出自己的立場。',
  'prompt.system.rule3': '- 訊息中以「[名稱]:」開頭的段落是其他成員或使用者說的話。你自己的回覆不要加名稱前綴,直接寫內容。',
  'prompt.system.agreed': '- 討論階段中,若你認為已有足夠共識、可以進入分工執行,請在回覆最後單獨一行寫上 {mark}。尚未有共識就不要寫。只有單獨成行才算數,在句子裡提到它不會被視為同意。',
  'prompt.system.ask': '- 討論階段中,若遇到必須由使用者決定、你無法自行判斷的關鍵問題,可以在回覆最後加一個提問區塊:單獨一行寫 {open},接著一行問題,再用「- 」條列 2~4 個可選答案,最後單獨一行寫 {close}。整場討論最多問 {max} 次,同一回合只會受理一題,不重要的事不要問,先把不需要答案就能做的部分講完。',
  'prompt.system.act': '- 執行與審查階段請根據指示實際操作,不要只給建議。',
  'prompt.system.projectRules': '這個工作目錄有自己的規範,寫在 {file},請一併遵守:\n---\n{rules}\n---',

  'prompt.task': '【任務】\n{task}\n',
  'prompt.discussLast': '這是最後一回合討論,請收斂並給出你的最終立場。若同意進入分工請在最後單獨一行寫 {mark}。',
  'prompt.discuss': '請發表你的看法(第 {round}/{max} 回合)。若你認為已可進入分工執行,請在最後單獨一行寫 {mark}。',

  'prompt.directed': '【指定回覆】使用者在最新一則訊息中用 @ 指定由你處理,請直接回應或完成使用者的要求。',
  'prompt.directedOthers': '同時被指定的還有 {others},各自處理即可,不需要等待對方。',
  'prompt.directedAlone': '這次只有你被指定,其他成員不會發言。',
  'prompt.directedCanEdit': '需要時可以直接在工作目錄({cwd})建立、修改檔案與執行指令。',
  'prompt.directedReadOnly': '你目前沒有修改檔案的權限,需要改動時請寫出完整內容或步驟。',

  'prompt.assign': '【分工】你是本次的主持人。請根據到目前為止的討論結果,把任務拆解並分配給以下成員:',
  'prompt.rosterItem': '- {code} =「{name}」({label}{readonly})',
  'prompt.rosterReadOnly': ',唯讀,不能修改檔案',
  'prompt.assignNoOverlap': '每位成員負責的檔案或模組盡量不要重疊,以免同時修改造成衝突。可以把某位成員的工作留空(不分配)。',
  'prompt.assignCodes': '`agent` 欄位請填上面的代號({codes}),不要填名稱。',
  'prompt.assignJson': '只輸出一段 JSON,不要加任何說明或 markdown 標記,格式如下:',
  'prompt.assignExample': '{"summary":"一句話說明整體方案","assignments":[{"agent":"A1","task":"具體、可直接執行的工作說明,包含要建立或修改的檔案"}]}',
  'prompt.unmatchedItem': '- `{agent}`:{task}',
  'prompt.planItem': '- **{name}**:{task}',

  'prompt.tests': '【寫測試】以下是分配給你的工作。這一回合**只寫測試,不要實作**(工作目錄:{cwd})。',
  'prompt.testsRules': '把任務的驗收條件寫成可以執行的測試:每一條要求一個案例,包含邊界與應該被拒絕的輸入。測試現在會是紅的(還沒有實作),那是正常的。用這個專案既有的測試框架與命名慣例;沒有的話用最簡單的做法(例如 node 的 assert)。寫完簡潔說明你涵蓋了哪些條件。',
  'prompt.executeTestFirst': '上一回合寫好的測試已經鎖住,不能修改({list})。請實作到這些測試通過;如果你認為某個測試本身寫錯了,在回報裡說明理由,不要改它。',
  'prompt.execute': '【執行】以下是分配給你的工作,請現在實際完成它(工作目錄:{cwd})。',
  'prompt.executeCanEdit': '你可以直接建立、修改檔案與執行指令。',
  'prompt.executeReadOnly': '注意:你目前沒有修改檔案的權限,請把要做的內容以完整程式碼或步驟寫出來。',
  'prompt.executeReport': '完成後請簡潔回報:做了什麼、建立或修改了哪些檔案、有什麼未完成或需要別人配合的地方。',
  'prompt.failedItem': '- **{name}**:{error}',

  'prompt.review': '【交叉審查】請檢查「{name}」剛完成的工作。請實際打開相關檔案確認,不要只看回報。',
  // 審查者無法自己讀檔時用這個版本:說清楚它看不到檔案,改動內容附在下面。
  // 以前對所有人都說「請打開檔案」,沒有工具的模型只好把工具呼叫當成文字寫出來假裝讀了。
  'prompt.reviewInline': '【交叉審查】請檢查「{name}」剛完成的工作。你沒有辦法自己打開檔案,所以下面附上了改動檔案目前的實際內容。請依這些內容確認,不要只看回報,也不要對沒附上的部分下結論。',
  'prompt.reviewReadTool': '下面沒附上的檔案、或被省略的部分,可以用 read_file 工具讀取。',
  // 工作目錄前後沒有差異(例如只做分析的任務)。只說「工作目錄裡沒偵測到」:略過的目錄與工作目錄以外都看不到。
  'prompt.reviewNoChanges': '【交叉審查】請檢查「{name}」剛完成的工作。這次工作目錄裡沒有偵測到檔案改動(不含 .git、node_modules 等目錄),請依任務與回報審查;若任務需要修改工作目錄裡的檔案卻沒有改,也請指出。',
  'prompt.reviewNoFilesChanged': '這次工作目錄裡沒有偵測到檔案改動(不含 .git、node_modules 等目錄)。若任務需要修改工作目錄裡的檔案卻沒有改,請指出。',
  'prompt.reviewAttached': '【交叉審查】請檢查「{name}」剛完成的工作。下面附上了改動檔案目前的實際內容,請依這些內容確認,不要只看回報。',
  'prompt.reviewUntouched': '【交叉審查】請檢查「{name}」剛完成的工作。依檔案工具的紀錄,「{name}」這次沒有修改任何檔案,請依任務與回報審查;若任務需要修改檔案卻沒有改,也請指出。',
  'prompt.reviewUntouchedLine': '依檔案工具的紀錄,「{name}」這次沒有修改任何檔案。若任務需要修改檔案卻沒有改,請指出。',
  'prompt.reviewReadOnly': '【交叉審查】請檢查「{name}」剛完成的工作。「{name}」這次沒有修改檔案的權限,它的工作不會改動檔案,請依任務與回報審查。',
  'prompt.reviewFilesAll': '這次任務所有執行成員改動的檔案(不一定都是「{name}」改的,請對照它的任務與回報):\n{list}',
  'prompt.reviewReadToolAny': '你可以用 read_file 工具讀取工作目錄裡的檔案,核對回報的內容。',
  'prompt.reviewReadToolUnlisted': '你可以用 read_file 工具讀取工作目錄裡的檔案。這次無法自動確定改了哪些檔案,請依任務與回報中提到的檔案自行讀取,實際讀過再下判斷;如果沒辦法讀到檔案,請說明無法驗證的部分,並且不要寫 {mark}。',
  'prompt.reviewInlineUnknown': '【交叉審查】請檢查「{name}」剛完成的工作。你沒有辦法自己打開檔案,這次也無法取得改動的檔案內容,所以你看不到實際的改動。請不要只憑回報判定沒有問題:說明你無法驗證哪些部分,並且不要寫 {mark}。',
  'prompt.reviewWhat': '先把任務的要求逐條列出,每一條都對照實際的檔案內容確認有沒有做到;規則複雜的地方,自己舉一兩個具體的輸入推演結果,不要只憑印象判斷。然後指出:明確的錯誤、沒做到的要求、與討論結論不一致之處。不影響正確性的改進建議另外列在最後,不算需要修正。請簡潔。',
  'prompt.reviewExecFailed': '注意:「{name}」的執行回合中途失敗({error}),檔案可能只改了一半。請確認工作目錄裡現在的檔案能不能用、任務有沒有完成。',
  'prompt.rereview': '這是修復後的複查:「{name}」已經依上一輪的審查意見修改過。請確認這些問題真的修好了,也確認修改沒有弄壞原本正確的地方。上一輪的審查意見:\n{notes}',
  'prompt.reviewFiles': '這次改動的檔案:\n{list}',
  'prompt.reviewContent': '改動檔案目前的內容:',
  'prompt.reviewFileBlock': '----- {path} -----\n{content}',
  'prompt.reviewFileUnreadable': '----- {path} -----\n(無法讀取:{error})',
  'prompt.reviewOmitted': '下面這些改動的檔案超過附上的數量或長度上限,沒有附上內容:\n{list}\n請不要對它們下結論,並在回覆中說明哪些部分因此無法驗證。',
  'prompt.reviewTruncated': '\n…(檔案過長,後面省略)…',
  // 「回報的結論錯了」也要算:評測(eval/ 的 analysis-only)裡,模型指出只分析的結論是錯的,
  // 卻因為「不需要改檔」照樣寫上標記,流程就把錯的結論放行了
  'prompt.reviewMark': '若你確認完全沒有問題,請在回覆的最後單獨一行寫上 {mark};只要有任何一項需要修正就不要寫。回報裡的說明或結論有錯,也算需要修正,即使不必改任何檔案。',
  'prompt.reviewAudit': '「{name}」這回合實際做過的檔案操作(由 app 紀錄,不是它自己說的):\n{list}',
  'prompt.reviewTask': '他負責的工作:\n{task}',
  'prompt.reviewReport': '他的回報:\n{report}',
  'prompt.reviewNote': '[{reviewer}]:\n{text}',

  'prompt.fix': '【修復】以下是其他成員對你剛才成果的審查意見。請現在就處理:能修的直接改檔案,不打算修的要明確說明理由。',
  'prompt.fixLast': '這是最後一輪修改:改完會再請審查者複查一次,但不會再有修改的機會。請簡潔回報你改了什麼、哪些沒改以及為什麼。',
  'prompt.fixTask': '你負責的工作:\n{task}',
  'prompt.fixNotes': '審查意見:\n{notes}',
  'prompt.fixFailedItem': '- **{name}**:{error}',

  'prompt.summary.failed': '以下成員的執行失敗,成果未納入審查,請在總結中明確指出:\n{list}',
  'prompt.summary.failedItem': '- {name}:{error}',
  'prompt.summary.reviewFailed': '以下交叉審查沒有完成,對應的成果等於沒有被檢查過,請在總結中明確標示為「未經審查」,不要說成沒有問題:\n{list}',
  'prompt.summary.reviewFailedItem': '- {reviewer} 審查 {target}:{error}',
  'prompt.summary.fixFailed': '以下成員的修復回合失敗,審查指出的問題仍然存在,請在總結中列為未解決:\n{list}',
  'prompt.summary.fixFailedItem': '- {name}:{error}\n  未處理的審查意見:\n{notes}',
  'prompt.summary.unresolved': '以下成員沒有修改檔案的權限,審查意見尚未處理,請在總結中列出並說明需要使用者做什麼:\n{list}',
  'prompt.summary.unresolvedItem': '- {name}:\n{notes}',
  'prompt.summary.git': '執行結束時,工作目錄的 git 變更如下。這是**當下的工作區狀態**,可能包含本次任務開始前就已存在的變更,請據實轉述、不要宣稱這些變更全部由本次任務產生:\n{changes}',
  'prompt.summary.divide': '【總結】請以主持人身分,根據執行回報、交叉審查與修復結果,簡潔總結:完成了什麼、審查發現並修掉了什麼、還有哪些未解決或需要使用者決定的事項。',
  'prompt.summary.discuss': '【總結】請以主持人身分,簡潔總結這次討論的結論、分歧點,以及建議的下一步。',
  'git.more': '- (另有 {n} 個變更檔案未列出)',
  'git.preexisting': '(執行前就已是變更狀態)',

  // ---------- 附件提示 ----------
  'attach.header': '【附件】使用者提供了 {n} 個附件:',
  'attach.path': '- {label}\n  路徑:{path}',
  'attach.imageInline': '- {label}(影像已隨訊息附上)',
  'attach.textInline': '- {label}(內容如下)',
  'attach.inlineCap': '- {label}(已達文字附件總內嵌上限,內容省略)',
  'attach.truncated': '\n…(檔案過長或已達附件總量上限,已截斷;完整內容見原始檔案)…',
  'attach.unreadable': '注意:你無法讀取 {names} 的內容,請不要憑檔名臆測,必要時請在回覆中說明。',

  // ---------- 匯出 ----------
  'export.title': '# AI Roundtable 對話',
  'export.user': '使用者',
  'export.agent': 'AI 成員',
  'export.system': '系統',
  'export.systemError': '系統錯誤',
  'export.systemWarn': '系統警告',
  'export.timeUnknown': '時間不明',
  'export.rawUsage': '> 原始用量：{fields}',
  'export.noFields': '無欄位',
  'export.usage': '> 用量：{fields}',
  'export.input': '輸入: {n}',
  'export.cached': '其中快取 {n}',
  'export.cacheWrite': '寫入快取 {n}',
  'export.cachedInput': '快取輸入: {n}',
  'export.output': '輸出: {n}',
  'export.cost': '成本: ${n}',
  'export.attachments': '> 附件：{list}',
  'export.unreviewed': '> ⚠ 尚未審查：這次改動沒有其他成員看過，請自行確認紅綠 diff。',
  'export.error': '> 錯誤：{text}',
  'export.empty': '_(無文字內容)_',
  'phase.idle': '閒置', 'phase.direct': '指定', 'phase.discuss': '討論', 'phase.divide': '分工',
  'phase.tests': '寫測試', 'phase.execute': '執行', 'phase.review': '審查', 'phase.repair': '修復', 'phase.summary': '總結',

  // ---------- 主程序 ----------
  'main.extNotFound': '找不到此 API 擴充，請先儲存設定',
  'main.extNoTest': '此擴充不支援 API 連線測試',
  'main.nothingToExport': '目前沒有可匯出的對話',
  'main.exportTitle': '匯出本次對話',
  'main.stillRunning': '目前仍在進行中,請先停止再載入歷史對話',
  'main.attachFilter': '可用附件',
  // 終端開不起來時,介面直接顯示這幾句(renderer 拿不到 pty 的細節)
  'terminal.noExpect': '這台 Mac 找不到 /usr/bin/expect,終端無法開啟',
  'terminal.tooMany': '最多同時開 {max} 個終端分頁,先關掉一個再開',
  'terminal.spawnFailed': '終端開不起來:{detail}',
  'adapter.missing': '找不到 CLI「{cli}」:對應的擴充可能已刪除或載入失敗,請到「設定 → CLI 與擴充」檢查',
  'adapter.failed': '{label} 執行失敗:{message}',
  // ---------- CLI 成員的執行期訊息 ----------
  // 這些會直接出現在對話泡泡的錯誤列與工具動作清單裡。錯誤原文(stderr)接在翻譯後面,不翻譯。
  'proc.seconds': '{n} 秒',
  'proc.minutes': '{n} 分鐘',
  'proc.minutesSeconds': '{m} 分 {s} 秒',
  'proc.timeout': '執行逾時({time})',
  'proc.timeoutSigterm': '執行逾時({time}),已送出 SIGTERM。',
  'proc.timeoutSigkill': '逾時行程未結束,已送出 SIGKILL。',
  'proc.notFound': '找不到指令 {bin}',
  'proc.checkTimeout': '逾時',
  'proc.checkSkipped': '(略過檢查)',
  'cli.spawnFailed': '無法啟動 {bin}:{detail}',
  'cli.timedOut': '{bin} 執行逾時',
  'cli.exitCode': '{bin} 結束代碼 {code}',
  'cli.failed': '{name} 執行失敗',
  'cli.reportedError': '{name} 回報錯誤',
  'cli.turnFailed': '{name} 回合失敗',
  'cli.customNotSet': '尚未設定自訂指令',
  'cli.customCommand': '自訂指令',
  'cli.unparsableJson': '無法解析 JSON 輸出:{detail}',
  // 未登入:給一句照做就能修好的話。指令放在 {cmd},介面另有複製按鈕。
  'cli.loginHint': '已安裝,但尚未登入。請開啟「終端機」,執行 {cmd} 並依畫面完成登入。',
  'cli.notLoggedIn': '{name} 尚未登入,或登入已過期。請開啟「終端機」,執行 {cmd} 並依畫面完成登入後再試一次。',
  'act.run': '執行指令:{detail}',
  'act.read': '讀取檔案:{detail}',
  'act.edit': '編輯檔案:{detail}',
  'act.write': '寫入檔案:{detail}',
  'act.delete': '刪除檔案:{detail}',
  'act.glob': '搜尋檔名:{detail}',
  'act.grep': '搜尋內容:{detail}',
  'act.ls': '列出目錄:{detail}',
  'act.tool': '工具:{detail}',
  'act.changes': '修改檔案({n})',
  'act.webSearch': '搜尋網路:{detail}',
  'cursor.effortIgnored': 'Cursor 的強度寫在模型名稱裡,已略過 {effort}',
  // ---------- 附件被拒絕的原因(顯示在輸入框「無法附加檔案:…」) ----------
  // 與上面的 attach.* 不同:那些是寫進提示詞給模型看的。
  'attachErr.notFormat': '內容不是 {fmt} 格式(副檔名與實際內容不符)',
  'attachErr.looksLike': '內容看起來是{kind},不是文字檔',
  'attachErr.nul': '文字檔不可包含 NUL 位元組(內容看起來是二進位檔)',
  'attachErr.utf8': '文字檔必須是有效的 UTF-8 編碼',
  'attachErr.json': '內容不是有效的 JSON 格式(副檔名與實際內容不符)',
  'attachErr.tooBig': '超過單檔上限 {limit}(這個檔 {size})',
  'attachErr.totalTooBig': '超過單次合計上限 {limit}',
  'attachErr.tooMany': '一次最多 {n} 個檔案',
  'attachErr.unsupported': '不支援的檔案類型「{ext}」,目前只收 {list}',
  'attachErr.noExt': '無副檔名',
  'attachErr.empty': '檔案是空的',
  'attachErr.notFile': '不是一般檔案',
  'attachErr.unrecognized': '附件內容格式無法辨識',
  'attachErr.noSource': '缺少檔案內容或路徑',
  'attachErr.badConversation': '無效的對話代號',
  'attachErr.unsafeName': '無法產生安全的儲存檔名',
  'attachErr.exists': '附件儲存路徑已存在',
  'attachErr.unknownSize': '未知大小',
  'attachErr.listSep': '、',
  'bin.elf': 'ELF 執行檔',
  'bin.macho': 'Mach-O 執行檔',
  'bin.machoFat': 'Mach-O 通用二進位',
  'bin.windows': 'Windows 執行檔',
  'bin.zip': 'ZIP / Office 壓縮檔',
  'bin.gzip': 'gzip 壓縮檔',
  // ---------- 歷史對話 ----------
  'session.notTranscript': '內容不是對話紀錄',
  'session.noMessages': '內容不是對話紀錄:缺少 messages 陣列',
  'session.badId': '無效的紀錄代號',
  'session.missing': '這筆紀錄已經不存在(可能已被刪除)',
  // ---------- 擴充的載入、儲存與 Ollama 一鍵設定 ----------
  'ext.duplicateId': 'id「{id}」與 {file} 重複',
  'ext.badJson': 'JSON 格式錯誤:{error}',
  'ext.badJsonUnsaved': 'JSON 格式錯誤,尚未儲存:{error}',
  'ext.badType': 'type 必須是 "cli" 或 "openai"(需要更多彈性時請改寫成 .js 外掛)',
  'ext.noRun': '必須匯出 run(agent, ctx, kit) 函式',
  'ext.badFileName': '檔名只能包含英數字、. _ -,並以 .json 或 .js 結尾',
  'ext.badTemplate': '範本名稱不正確',
  'ext.exists': '已經有名為 {file} 的擴充',
  'ext.noUserDir': '找不到擴充設定目錄',
  'ext.noTemplateDir': '找不到內建 Ollama 範本目錄',
  'ext.ollamaTemplateUnreadable': '無法讀取 Ollama 範本:{error}',
  'ext.ollamaConfigUnreadable': '無法讀取現有 Ollama 設定:{error}',
  'ext.ollamaModelMissing': 'Ollama 找不到模型「{model}」,請先下載後再試一次',
  'ext.noKeychain': '系統安全儲存目前不可用',
  'ext.legacyKeyFailed': '偵測到舊版明文 API key,但{error}。請設定環境變數後移除檔案中的 apiKey',
  'ext.legacyKeyMigrated': '已將舊版明文 API key 移至系統安全儲存。',
  // ---------- 擴充設定的驗證錯誤(寫自訂 JSON 時看到) ----------
  // 句型重複度很高,所以用 {field} 參數化,不逐句翻譯。欄位名稱是協定,不翻譯。
  'spec.contentObject': '內容必須是物件',
  'spec.badId': 'id 必須是 1–64 個英數字,可含 . _ -,且以英數字開頭',
  'spec.modelsShape': 'models 必須是陣列或 "auto"',
  'spec.usageShape': 'usageShape 必須是 {list};不填則依欄位特徵自動判斷',
  'spec.binShape': 'bin 必須是指令名稱或路徑',
  'spec.baseUrl': 'baseUrl 必須是 http:// 或 https:// 開頭的網址',
  'spec.apiKeyEnv': 'apiKeyEnv 必須是環境變數名稱',
  'spec.plainApiKey': 'apiKey 明文欄位已停用,請在擴充設定的 API key 欄位安全移轉',
  'spec.mustBeObject': '{field} 必須是物件',
  'spec.mustBeArray': '{field} 必須是陣列',
  'spec.mustBeString': '{field} 必須是字串',
  'spec.mustBeBoolean': '{field} 必須是布林值',
  'spec.mustBePositive': '{field} 必須是正數',
  'spec.mustBePositiveInt': '{field} 必須是正整數',
  'spec.mustBeOneOf': '{field} 必須是 {list}',
  'spec.onlyAccepts': '{field} 只接受 {list}',
  'spec.noDuplicates': '{field} 不可重複',
  'spec.badFormat': '{field} 格式不正確',
  'spec.badRegex': '{field} 不是有效的正規表示式:{error}',
  'spec.requiresTogether': '{a}=true 時必須明確設定 {b}=true',
  'spec.listSep': '、',
  'spec.or': ' 或 ',
  // ---------- 反例與棘輪(見 src/counterexample.ts、src/ratchet.ts、src/corpus.ts) ----------
  'ce.untitled': '(未命名)',
  'ce.noOutput': '(沒有輸出)',
  'ce.stopped': '已停止',
  'ce.dropLimit': '超過一次審查最多 3 個反例的上限',
  'ce.dropTooLong': '反例太長',
  'ce.dropEmpty': '反例是空的,或區塊沒有收尾',
  'ce.fixNotes': '**下面是 app 自己跑出來的反例,不是誰的意見。** 每一段都在現在這份程式上真的失敗了;修好之後它們必須全部以結束碼 0 通過:\n\n{list}',
  'ce.fixItem': '反例「{title}」(由 {reviewer} 提出),目前以結束碼 {code} 失敗:\n```js\n{source}\n```\n輸出:\n```\n{output}\n```',
  'ce.status': 'app 重跑反例的結果:\n{list}',
  'ce.statusPassed': '- ✓ 「{title}」現在通過了',
  'ce.statusFailed': '- ✗ 「{title}」仍然失敗:\n```\n{output}\n```',
  'ce.statusUnusable': '- ? 「{title}」這次跑不起來,無法判定:\n```\n{output}\n```',
  'ratchet.itemSyntax': '- 檔案 `{label}` 載不起來了',
  'ratchet.itemGate': '- 驗證指令 `{label}`',
  'ratchet.itemCounterexample': '- 反例「{label}」',
  'sys.baselineClean': '基準線:任務開始前的 {total} 道關卡全部通過。接下來的改動不可以讓其中任何一道變成不通過。',
  'sys.baselineFailing': '基準線:任務開始前 {total} 道關卡通過 {passed} 道。下面這幾道本來就沒過,不算這次任務的責任——棘輪比的是有沒有變糟,不是有沒有全過:\n{list}',
  'sys.ceDropped': '這幾個反例沒有收下:\n{list}',
  'sys.ceDroppedItem': '- {reviewer} 的「{title}」:{reason}',
  'sys.ceItem': '- 「{title}」(由 {reviewer} 提出)',
  'sys.ceConfirmed': 'app 跑過審查者附上的反例,其中 {n} 個真的重現了問題。它們是這次修復回合的驗收標準:\n{list}',
  'sys.ceUnsubstantiated': '這幾個反例在現在這份程式上跑起來是通過的——審查者指出了問題,卻舉不出可重現的例子。它們不列入必須修復的項目:\n{list}',
  'sys.ceUnusable': '這幾個反例本身跑不起來(寫檔失敗、逾時或無法啟動),既不算問題確認了,也不算沒問題:\n{list}',
  'sys.corpusSaved': '{n} 個確認過的反例已存進專案的反例語料庫(目前共 {total} 個),放在工作目錄的 `.roundtable/counterexamples.json`。之後每次任務開始前都會再跑一遍。',
  'sys.corpusFull': '{n} 個反例沒有存進語料庫:已達上限。',
  'sys.corpusFailed': '反例語料庫寫入失敗:{error}',
  'sys.ratchetRegressed': '**有關卡從通過變成不通過:**\n{list}',
  'sys.ratchetInherited': '語料庫裡累積下來的反例有幾道現在不過了。它們不會觸發自動回退——舊反例也可能測錯需求,或者這次的任務本來就是要改掉那個行為——但請確認一下:\n{list}',
  'sys.ratchetImproved': '這幾道關卡從不通過變成通過了:\n{list}',
  'prompt.fixCounterexampleRule': '上面的反例就是這一回合的驗收標準,而且由 app 自己執行:說「已經修好了」不算數,要讓那些腳本真的以結束碼 0 結束。不要修改反例本身。',
  'prompt.reviewCounterexample': '如果你找到明確的錯誤,請盡量附上可以執行的反例:用 ```counterexample 開頭的程式碼區塊(開頭那行的 ``` 後面可以接一句話當標題),裡面寫一段獨立的 Node.js 腳本——require 或 import 這次改動的檔案,用具體的輸入呼叫它,行為不正確時丟出錯誤(例如 node:assert)。腳本會放在工作目錄最上層執行,相對路徑直接寫 ./檔名 即可。它在現在這份程式上必須失敗;app 會自己跑一次確認,跑不出問題的反例不算數。最多 3 個。沒把握寫出可執行的反例時,照常用文字說明就好。',
};

const EN: Record<string, Entry> = {
  'api.missingKeyEnv': 'Missing API key: enter it in Settings → CLIs & extensions, or set {env}',
  'api.missingKey': 'Missing API key: enter and save it in Settings → CLIs & extensions',
  'api.invalidKey': 'API key rejected by {service}: enter a new key in Settings → CLIs & extensions',
  'api.service': 'the service',
  'api.modelsTimeout': 'Timed out fetching the model list',
  'api.connectionTimeout': 'Connection test timed out',
  'api.connected': 'Connected to {url}',
  'api.networkHint': 'Cannot reach the service. Check your network and try again',
  'api.localHint': 'Check that the service is running and reachable',
  'api.noModel': 'No model selected: choose one in member settings or set defaultModel in extension settings',
  'api.runTimeout': 'API request timed out ({duration})',
  'api.stopped': 'Stopped',
  'api.cannotConnect': 'Cannot connect to {url}: {error}',
  'api.fileToolsFailed': 'Could not enable file tools: {error}',
  'api.tooManyTools': 'This batch exceeds the limit of {n} tool calls per turn. No calls were run; reduce the batch size',
  'api.toolRunning': '{name} running',
  'api.readToolsFallback': 'The request with tools was rejected ({error}); resent once without tools',
  'api.ephemeralDropped': '(File contents attached here were for that turn only and have been removed from memory.)',
  'api.readDropped': '(Read {n} characters; the content was removed from memory, read the file again if needed)',
  'ext.timeoutHint': 'If this model needs longer, edit this extension in Settings → CLIs & extensions and raise “Time limit per turn”.',
  'api.toolTruncated': '… (truncated)',
  'api.imagesDropped': '({n} image(s) attached in an earlier turn were removed from memory)',
  'api.readToolsUnavailable': '(The read_file tool is not available for this model this time. Do not call any tools; answer from the content of this prompt only.)',
  // File tools: descriptions, errors and summaries. The model reads them, and so does the user in the tool audit
  'ft.def.read': 'Read a UTF-8 text file in the working directory. Call it before modifying an existing file, and pass its sha256 to the write tool.',
  'ft.def.path': 'Path relative to the working directory',
  'ft.def.offset': 'Character offset to start from; default 0',
  'ft.def.limit': 'Maximum characters to return; default 65536. Larger values are clamped to 65536. truncated=true means some content was omitted',
  'ft.def.write': 'Create a small text file, or overwrite a whole file whose sha256 has not changed. Existing files require expectedSha256; new files require createOnly=true.',
  'ft.def.content': 'The complete UTF-8 text content, up to 256 KB',
  'ft.def.createOnly': 'Must be true when creating a new file; fails if the file already exists',
  'ft.def.reason': 'Why you are making this change; recorded for the review',
  'ft.def.replace': 'Replace exact text in part of a file. By default oldText must occur exactly once; to replace several occurrences, set replaceAll=true.',
  'ft.def.oldText': 'The exact original text, at least 24 characters',
  'ft.def.newText': 'The replacement text',
  'ft.def.replaceAll': 'Explicitly allow replacing every match; default false',
  'ft.autoExecDir': 'Cannot write files under {dir}: files there run automatically',
  'ft.autoExecFile': 'Cannot write {file}: this file runs automatically',
  'ft.executable': 'Cannot write {file}: it has execute permission',
  'ft.vcs': 'Version-control internals (.git, .hg, .svn) cannot be read or modified',
  'ft.pathEmpty': 'path must be a non-empty relative path',
  'ft.pathAbsolute': 'path must be relative to the working directory',
  'ft.pathNul': 'path must not contain NUL',
  'ft.textNul': 'Only UTF-8 text files are allowed; NUL is not',
  'ft.textInvalid': 'Only valid UTF-8 text files are allowed',
  'ft.contentString': 'content must be a string',
  'ft.contentUtf8': 'content must be valid UTF-8 text',
  'ft.contentNul': 'content must not contain NUL',
  'ft.contentTooBig': 'The content exceeds the {max}-byte limit',
  'ft.notRegular': 'Only regular files are allowed',
  'ft.fileTooBig': 'The file exceeds the {max}-byte limit',
  'ft.noWorkdir': 'The working directory does not exist',
  'ft.workdirNotDir': 'The working directory is not a folder',
  'ft.outside': 'The path is outside the working directory',
  'ft.symlinkWrite': 'Writing through a symbolic link is not allowed',
  'ft.symlinkOutside': 'The symbolic link points outside the working directory',
  'ft.noParent': 'The parent folder of the new file does not exist',
  'ft.outputFull': 'The tool output limit for this turn has been reached',
  'ft.tooManyCalls': 'No more than {n} tool calls are allowed in one turn',
  'ft.argsTooBig': 'The tool arguments exceed the {max}-character limit',
  'ft.outputReserve': 'Not enough tool output allowance left in this turn; the file was not modified',
  'ft.argsJson': 'The tool arguments are not valid JSON',
  'ft.argsObject': 'The tool arguments must be an object',
  'ft.readOnly': 'This turn can only read files, not modify them',
  'ft.lockedTest': '`{path}` is a test file that existed before the task, and the repair round may not modify it. Make the tests pass by changing the implementation; if the test itself is wrong, say so in your report instead of editing it',
  'ft.unknownTool': 'Unsupported tool: {name}',
  'ft.offset': 'offset must be a non-negative integer',
  'ft.limit': 'limit must be an integer of at least 1 (a value above {max} is clamped to the limit instead of failing)',
  'ft.reason': 'reason must be 1–500 characters',
  'ft.createExists': 'createOnly=true, but the file already exists',
  'ft.createNeedsFlag': 'Creating a new file requires createOnly=true',
  'ft.createNoSha': 'Do not pass expectedSha256 when creating a new file',
  'ft.overwriteNeedsSha': 'Overwriting an existing file requires the expectedSha256 returned by read_file',
  'ft.shaMismatch': 'The file was changed by another member and its sha256 no longer matches; call read_file again',
  'ft.changedBeforeWrite': 'The file changed again before writing; call read_file again',
  'ft.oldTextShort': 'oldText needs at least {n} non-whitespace characters',
  'ft.newTextString': 'newText must be a string',
  'ft.replaceUtf8': 'The texts must be valid UTF-8 without NUL',
  'ft.controlChars': 'The texts must not contain control characters (except tab, newline and carriage return)',
  'ft.replaceNeedsSha': 'replace_text requires the expectedSha256 returned by read_file',
  'ft.notFound': 'oldText was not found; the file was not modified',
  'ft.multiple': 'oldText occurs {n} times; give longer, unique text or set replaceAll=true explicitly',
  'ft.summaryOk': '{name} {path} done{counts}',
  'ft.summaryFail': '{name} {path} failed: {error}',
  'ft.unknownError': 'unknown error',
  'api.toolNoProgress': 'Every tool call failed for {n} rounds in a row, so the turn stopped: continuing would repeat the same error',
  'api.toolRoundsExceeded': 'Stopped after {n} model tool call rounds to prevent an infinite loop',
  'api.imageFallback': 'This model rejected images ({error}); retrying with text only and omitting {n} images',
  'api.startOllama': 'Start Ollama first',
  'api.ollamaTestFailed': 'Could not test the Ollama connection',
  'api.ollamaConnectFailed': 'Could not connect to Ollama',
  'sys.error': 'Error: {message}',
  'sys.noAgents': 'No members are enabled. Add or enable a member in the sidebar first.',
  'sys.cwdFailed': 'Could not create the working directory {cwd}: {message}',
  'sys.stopped': 'Stopped.',
  'sys.stageFailed': 'Could not copy attachments into the working directory: {error}',
  'sys.unstageFailed': 'Could not remove the attachment staging folder ({dir}): {error}',
  'sys.agreed': 'Everyone agreed in round {round}.',
  'sys.askAnswered': 'Answering {name}: \n{answer}',
  'sys.askDeferred': "{name}'s question is yours to decide; carry on with your own judgement.",
  'sys.maxRoundsDivide': 'Reached the round limit ({max}). Moving on to dividing the work.',
  'sys.maxRoundsSummary': 'Reached the round limit ({max}). The lead will summarize.',
  'sys.unmatched': '**Some work could not be matched to a member** and was skipped:\n{list}',
  'sys.plan': (p) => `**Work plan**${p.summary ? `: ${p.summary}` : ''}\n\n${p.lines}`,
  'sys.taskSummary.title': '**Task result** · took {duration}',
  'sys.taskSummary.member': '- {name}: {outcome}{reviewers}',
  'sys.taskSummary.reviewedBy': ' (reviewed by {names})',
  'sys.taskSummary.files': 'Changed {n} files:',
  'sys.taskSummary.file': '- {path} +{added} −{removed}',
  'sys.taskSummary.noFiles': 'This task changed no files.',
  'sys.taskSummary.usage': 'input {input} / output {output} tokens',
  'sys.taskSummary.verify.passed': 'executed checks passed (including project verify commands)',
  'sys.taskSummary.verify.syntax-only': 'syntax check passed only; not merge-ready',
  'sys.taskSummary.evidence': 'Verification record: syntax checked for {n} JS / JSON files',
    'sys.taskSummary.freshness.current': 'Workspace fingerprints matched during checks (dependencies, caches and version-control directories excluded).',
    'sys.taskSummary.freshness.stale': 'File versions changed; this evidence needs verification again.',
    'sys.taskSummary.freshness.unknown': 'Evidence has not been matched to the current file versions.',
    'sys.taskSummary.previousVerification': 'Previous verification record:',
    'sys.taskSummary.reviewStale': 'Changed file versions have not been reviewed again; original verdicts are historical.',
    'sys.reverifyBusy': 'Verification or restore is in progress. Wait until it finishes.',
    'sys.reverifyUnavailable': 'Cannot reverify: the task, working directory or settings changed, or the operation was stopped.',
    'phase.verify': 'Reverify',
  'sys.taskSummary.checkedAt': 'Checked at {time}. Later edits are not verified.',
  'sys.taskSummary.noCommands': 'No project verification commands ran',
  'sys.taskSummary.unknownScope': 'Changed-file scope is unknown',
  'sys.taskSummary.check.passed': 'Passed',
  'sys.taskSummary.check.failed': 'Failed',
  'sys.taskSummary.check.timeout': 'Timed out',
  'sys.taskSummary.check.unavailable': 'Check unavailable',
  'sys.taskSummary.check.unsupported': 'Format not supported by built-in syntax checks',
  'sys.taskSummary.check.limit': 'Syntax check limit reached',
  'sys.taskSummary.check.skipped': 'Not run after earlier failure',
  'sys.taskSummary.verify.failed': 'automatic verification failed',
  'sys.taskSummary.verify.none': 'no automatic verification',
  'sys.taskSummary.repairBroke': '⚠ The repair round made things worse: checks that passed after execution failed after repair.',
  'sys.taskSummary.rollbackRepair': 'The repair round was automatically rolled back; execute-round changes were kept. Verification above describes the restored files; the requirements are still unmet.',
  'sys.taskSummary.rollbackTask': 'The working directory was automatically restored to its pre-task state. Verification above describes the restored files; the requirements are still unmet.',
  'sys.taskSummary.rollbackPartial': 'Automatic rollback is incomplete; some files could not be restored. Check the rollback log and working directory.',
  'sys.taskSummary.rollbackUnavailable': 'No baseline was available, so automatic rollback was not performed. Check the files in the working directory.',
  'sys.taskSummary.testsTouched': 'existing tests were modified',
  'sys.taskOutcome.approved': '✓ Approved',
  'sys.taskOutcome.repaired': 'Fixed after review (not re-reviewed)',
  'sys.taskOutcome.unresolved': '⚠ Unresolved issues',
  'sys.taskOutcome.unreviewed': 'Not reviewed',
  'sys.taskOutcome.failed': '✗ Failed',
  'sys.planNoMatch': "None of the lead's assignments matched a member. Trying again.",
  'sys.planUnparsable': "Could not parse the lead's work plan. Trying again.",
  'sys.planLeadFailed': 'The lead "{name}" did not respond, so no work plan could be made. Check that member\'s setup (the status bar at the bottom left opens it).',
  'sys.planFailed': 'Dividing the work failed, so nothing was executed. Try the "Discussion only" mode, or pick a different lead.',
  'sys.nobodyAssigned': 'No member was assigned any work.',
  'verify.syntaxFailed': '**The automatic syntax check failed**; these files cannot be loaded:\n{list}',
  'verify.syntaxItem': '- `{file}`: {error}',
  'verify.commandFailed': '**A verify command failed**: `{command}` (exit code {code}). Output:\n```\n{output}\n```',
  'verify.commandTimeout': '**A verify command timed out**: `{command}`. Output:\n```\n{output}\n```',
  'verify.commandNotFound': '**A command set in Settings → General → Verify command was not found**: `{command}`, so nothing was actually verified. Output:\n```\n{output}\n```',
  'verify.gatesPassed': 'These passed before it: {list}',
  'verify.noOutput': '(no output)',
  'sys.testsTouched': '**This change modified test files that existed before the task**:\n{list}\nTests should pass by changing the implementation, not the tests. Check that these changes were necessary.',
  'sys.testsLockedFixed': 'The repair round modified existing test files:\n{list}',
  'prompt.reviewConflict': 'Note: these files were changed by more than one member ({list}). If isolated directories were used, overlapping files were not merged back and each version remains there; otherwise a later write overwrote an earlier one. Check that the working directory is complete.',
  'prompt.reviewTests': 'Note: this change modified test files that existed before the task ({list}). Check carefully that these tests were not loosened, trimmed, or had their expected values changed to make the result pass; if the tests were weakened, "tests pass" means nothing.',
  'prompt.fixTestLock': 'While repairing, do not modify test files that existed before the task ({list}). Make the tests pass by changing the implementation; if you believe a test itself is wrong, explain why in your report instead of editing it.',
  'sys.autoRevertedFix': 'The repair round regressed, so it was rolled back: {restored} files restored, {deleted} added files deleted. The execute round is kept and will be verified again.',
  'sys.autoReverted': 'Automatic checks failed, so the working directory was restored to its pre-task state: {restored} files restored, {deleted} deleted. Verification will run again; the task is still incomplete.',
  'sys.autoRevertPartly': 'Automatic checks failed, and the regression was rolled back as far as possible ({restored} files restored, {deleted} deleted), but these files could not be restored; please check them yourself:\n{list}',
  'sys.autoRevertUnavailable': 'Automatic checks failed, but no rollback baseline is available. No automatic restore was performed; check the files in the working directory.',
  'sys.rollbackUnresolved': 'The final checks failed or the repair round regressed, so the app initiated automatic rollback. The work is still undelivered; rollback does not mean the requirements were met. The rollback result and subsequent verification are reported separately.',
  'sys.revertedFix': 'Rolled back the repair round: {restored} files restored, {deleted} added files deleted. The work from the execute round is kept.',
  'sys.reverted': "This task's changes were reverted: {restored} files restored, {deleted} deleted. The working directory is back to how it was before the task.",
  'sys.revertPartly': 'Most changes were reverted ({restored} files restored, {deleted} deleted), but these files could not be restored; please check them yourself:\n{list}',
  'sys.projectRules': 'Applied the project conventions from the working directory: `{file}`{truncated}',
  'sys.projectRulesTruncated': ' (too long; only the first part is used)',
  'sys.parallelConflict': '**Some files were changed by more than one member.** Overlapping files were not merged back into the working directory; each version remains in its isolated directory:\n{list}',
  'sys.parallelConflictItem': '- `{file}`: {names}',
  'sys.lanesReady': 'Parallel execution used a separate directory per member. Non-overlapping changes are merged back afterwards.',
  'sys.lanesUnavailable': 'Could not prepare isolated directories ({error}). Members will run sequentially in the original working directory, without concurrent writes.',
  'sys.lanesKept': 'Unmerged changes remain in isolated directories at `{dir}`. Recover the versions you need before cleaning them up yourself.',
  'sys.sharedConflict': '**Multiple members edited the same files.** Later writes may have overwritten earlier content:\n{list}',
  'sys.mergeFailed': 'These changes could not be merged safely. Unmerged versions remain in their isolated directories: {list}',
  'sys.mergeUnresolved': 'Some isolated changes remain unmerged, so the work is not delivered. Manual resolution is required; a passing review is not completion.',
  'sys.repairHandoff': '{repairer} identified issues in {author}\'s work and will repair it directly. {reviewer} will independently re-check the repair.',
  'prompt.repairHandoff': 'You are taking over repairs to {name}\'s work. Read the current files and fix the issues you identified directly, rather than only returning suggestions.',
  'prompt.repairedBy': '{name} performed this repair. Independently check the actual changes instead of trusting the repair report.',
  'prompt.executeLane': 'Edit only this isolated directory. After the turn, the app merges changes that do not overlap with another member back into the working directory.',
  'sys.testsWritten': 'Tests are in place and cannot be modified during implementation:\n{list}',
  'sys.testsNone': 'No test files were written this turn, so the implementation has no tests to follow.',
  'sys.verifyOk': 'Automatic verification passed.',
  'sys.verifyFailed': 'Automatic verification failed:\n{notes}',
  'sys.verifyNone': 'There was nothing to verify automatically (no .js/.json changes and no verify command).',
  'prompt.reviewVerify': 'The app ran this itself; it is not what any member said:\n{notes}\nTreat these as problems that must be handled.',
  'prompt.reviewVerifyOk': 'These changes passed the app\'s automatic verification (the changed files load{command}).',
  'prompt.reviewVerifyCommand': ', and the verify command succeeded',
  'prompt.fixVerify': 'Result of the automatic verification, which the app actually ran rather than anyone\'s opinion:\n{notes}',
  'sys.execFailed': '**Execution failed** for these members. Their work will not be reviewed:\n{list}',
  'sys.execSalvaged': '**Execution stopped partway**, but files were already changed, so the work still goes to review to check whether what was left behind works:\n{list}',
  'sys.rereviewIssues': 'After the re-check, {names} still has issues; they go into the summary.',
  'sys.noReport': 'no report produced',
  'sys.noReviewer': 'No other member can act as reviewer (only one member is enabled). Skipping cross-review.',
  'sys.toolAudit': (p: Params) => `**File operations by ${p.name}**\n${p.list}`,
  'sys.toolUnknownError': 'unknown error',
  'sys.toolStatsApprox': ', approximate — check the actual file changes',
  'sys.reviewFailed': '**Cross-review failed.** These reviews produced no result, which does not mean the work is fine:\n{list}',
  'sys.reviewFailedItem': '- **{reviewer}** reviewing "{target}": {error}',
  'sys.noReviewText': 'no review produced',
  'sys.noSuccessfulReview': 'No review succeeded. Skipping the repair round.',
  'sys.noIssues': 'Cross-review found no issues. Skipping the repair round.',
  'sys.unresolved': '{names} cannot edit files. The review comments go straight into the summary.',
  'sys.fixFailed': '**Repair failed.** Review comments for these members remain unaddressed:\n{list}',
  'sys.retryBusy': 'A task is running. Wait for it to finish before retrying.',
  'sys.retryNotAllowed': 'This message cannot be retried (only the latest failed direct reply can be).',
  'sys.unfinishedOnSave': 'This message had not finished when it was saved',

  'transcript.new': '[New messages]',
  'transcript.sofar': '[Conversation so far]',
  'transcript.user': 'User',
  'transcript.system': 'System',
  'transcript.omitted': '…({n} messages in the middle omitted)…',
  'transcript.clipped': '\n…(this message was too long and has been truncated)…',

  'prompt.system.intro': 'You are an AI assistant named "{name}" taking part in a multi-AI roundtable with other AI assistants ({others}), moderated by the user.',
  'prompt.system.noOthers': '(no other members right now)',
  'prompt.system.persona': 'Your role and personality: {persona}',
  'prompt.system.noPersona': '(not set)',
  'prompt.system.rules': 'Rules:',
  'prompt.system.rule1': '- Reply in {lang}. Be concise and focused; do not repeat what others have already said.',
  'prompt.system.rule2': '- Respond concretely to the other members: agree, disagree (with reasons) or add to their points. When there is disagreement, state your own position clearly.',
  'prompt.system.rule3': '- Paragraphs starting with "[Name]:" are what other members or the user said. Do not prefix your own reply with a name; just write the content.',
  'prompt.system.agreed': '- During discussion, if you believe there is enough agreement to move on to dividing and executing the work, end your reply with {mark} on a line by itself. Do not write it before there is agreement. Only a line by itself counts; mentioning it inside a sentence is not agreement.',
  'prompt.system.ask': '- During discussion, if you hit a key decision only the user can make, you may end your reply with a question block: {open} on a line by itself, then the question on one line, then 2-4 possible answers as "- " bullets, and {close} on a line by itself. You may ask at most {max} times per discussion and only one question per round is accepted, so do not ask about minor things, and cover everything you can decide without an answer first.',
  'prompt.system.act': '- In the execution and review phases, actually do the work as instructed instead of only giving advice.',
  'prompt.system.projectRules': 'This working directory has its own conventions, written in {file}. Follow them as well:\n---\n{rules}\n---',

  'prompt.task': '[Task]\n{task}\n',
  'prompt.discussLast': 'This is the final round of discussion. Converge and give your final position. If you agree to move on to dividing the work, end with {mark} on a line by itself.',
  'prompt.discuss': 'Share your view (round {round}/{max}). If you think the group can move on to dividing and executing the work, end with {mark} on a line by itself.',

  'prompt.directed': '[Direct reply] The user addressed you with @ in the latest message. Respond directly or carry out the request.',
  'prompt.directedOthers': '{others} were addressed at the same time. Handle your part; there is no need to wait for them.',
  'prompt.directedAlone': 'Only you were addressed this time. The other members will not speak.',
  'prompt.directedCanEdit': 'If needed, you can create and edit files and run commands directly in the working directory ({cwd}).',
  'prompt.directedReadOnly': 'You currently cannot edit files. When changes are needed, write out the full content or the steps.',

  'prompt.assign': '[Divide the work] You are the lead this time. Based on the discussion so far, break the task down and assign it to these members:',
  'prompt.rosterItem': '- {code} = "{name}" ({label}{readonly})',
  'prompt.rosterReadOnly': ', read-only, cannot edit files',
  'prompt.assignNoOverlap': 'Keep the files or modules each member owns from overlapping, so concurrent edits do not conflict. A member may be left without work.',
  'prompt.assignCodes': 'Fill the `agent` field with the codes above ({codes}), not names.',
  'prompt.assignJson': 'Output a single JSON object with no explanation or markdown fences, in this format:',
  'prompt.assignExample': '{"summary":"one sentence describing the overall approach","assignments":[{"agent":"A1","task":"a concrete, directly executable description of the work, including the files to create or change"}]}',
  'prompt.unmatchedItem': '- `{agent}`: {task}',
  'prompt.planItem': '- **{name}**: {task}',

  'prompt.tests': '[Write tests] Below is the work assigned to you. This turn is **tests only, no implementation** (working directory: {cwd}).',
  'prompt.testsRules': "Turn the acceptance criteria into runnable tests: one case per requirement, including edge cases and inputs that must be rejected. The tests will fail for now because there is no implementation yet; that is expected. Use the project's existing test framework and naming conventions, or the simplest thing that works (for example node's assert) if there is none. When you are done, briefly say which criteria you covered.",
  'prompt.executeTestFirst': 'The tests written in the previous turn are locked and cannot be modified ({list}). Implement until those tests pass; if you believe a test itself is wrong, explain why in your report instead of editing it.',
  'prompt.execute': '[Execute] Below is the work assigned to you. Complete it now (working directory: {cwd}).',
  'prompt.executeCanEdit': 'You can create and edit files and run commands directly.',
  'prompt.executeReadOnly': 'Note: you currently cannot edit files. Write out the full code or the steps for what needs to be done.',
  'prompt.executeReport': 'When done, report briefly: what you did, which files you created or changed, and anything unfinished or needing someone else.',
  'prompt.failedItem': '- **{name}**: {error}',

  'prompt.review': '[Cross-review] Check the work "{name}" just completed. Open the relevant files and verify; do not rely on the report alone.',
  'prompt.reviewInline': '[Cross-review] Check the work "{name}" just completed. You cannot open files yourself, so the current contents of the changed files are included below. Verify against them, do not rely on the report alone, and do not draw conclusions about parts that are not shown.',
  'prompt.reviewReadTool': 'Files or parts that are not included below can be read with the read_file tool.',
  'prompt.reviewNoChanges': '[Cross-review] Check the work "{name}" just completed. No file changes were detected in the working directory this time (.git, node_modules and similar folders are not checked), so review it from the task and the report; if the task needed files in the working directory to change and they did not, point that out.',
  'prompt.reviewNoFilesChanged': 'No file changes were detected in the working directory this time (.git, node_modules and similar folders are not checked). If the task needed files in the working directory to change and they did not, point that out.',
  'prompt.reviewAttached': '[Cross-review] Check the work "{name}" just completed. The current contents of the changed files are included below; verify against them and do not rely on the report alone.',
  'prompt.reviewUntouched': '[Cross-review] Check the work "{name}" just completed. According to its file tool records, "{name}" changed no files this time; review it from the task and the report, and if the task needed file changes that were not made, point that out.',
  'prompt.reviewUntouchedLine': 'According to its file tool records, "{name}" changed no files this time. If the task needed file changes that were not made, point that out.',
  'prompt.reviewReadOnly': '[Cross-review] Check the work "{name}" just completed. "{name}" had no permission to change files this time, so its work does not change files; review it from the task and the report.',
  'prompt.reviewFilesAll': 'Files changed in this task by all executing members (not necessarily by "{name}"; compare with its task and report):\n{list}',
  'prompt.reviewReadToolAny': 'You can read files in the working directory with the read_file tool to check the report.',
  'prompt.reviewReadToolUnlisted': 'You can read files in the working directory with the read_file tool. The changed files could not be determined this time, so read the files mentioned in the task and the report yourself before you decide; if you cannot read them, say what you could not verify and do not write {mark}.',
  'prompt.reviewInlineUnknown': '[Cross-review] Check the work "{name}" just completed. You cannot open files yourself, and the changed file contents could not be obtained this time, so you cannot see the actual changes. Do not judge the work fine from the report alone: say what you could not verify, and do not write {mark}.',
  'prompt.reviewWhat': 'First list the requirements of the task one by one, and check each against the actual file contents; where the rules are intricate, work through one or two concrete inputs yourself instead of judging from memory. Then point out: clear mistakes, requirements that are not met, and anything inconsistent with the discussion. List improvements that do not affect correctness separately at the end; they do not count as something to fix. Be concise.',
  'prompt.reviewExecFailed': 'Note: the execution turn of "{name}" stopped partway ({error}), so the files may be only half changed. Check whether the files now in the working directory work and whether the task is done.',
  'prompt.rereview': 'This is the re-check after repair: "{name}" has changed the work based on the previous review. Confirm those problems are really fixed, and that the changes did not break anything that was correct before. The previous review:\n{notes}',
  'prompt.reviewFiles': 'Files changed in this task:\n{list}',
  'prompt.reviewContent': 'Current contents of the changed files:',
  'prompt.reviewFileBlock': '----- {path} -----\n{content}',
  'prompt.reviewFileUnreadable': '----- {path} -----\n(could not read: {error})',
  'prompt.reviewOmitted': 'The following changed files exceeded the number or size limit for attached content and are not included:\n{list}\nDo not draw conclusions about them, and say in your reply what you could not verify as a result.',
  'prompt.reviewTruncated': '\n…(file too long, the rest is omitted)…',
  'prompt.reviewMark': 'If you confirm there are no issues at all, end your reply with {mark} on a line by itself. Leave it out if anything needs fixing. A wrong statement or conclusion in the report counts as something to fix, even when no file needs to change.',
  'prompt.reviewAudit': 'File operations "{name}" actually performed this turn, as recorded by the app rather than reported by the member:\n{list}',
  'prompt.reviewTask': 'Their assigned work:\n{task}',
  'prompt.reviewReport': 'Their report:\n{report}',
  'prompt.reviewNote': '[{reviewer}]:\n{text}',

  'prompt.fix': '[Repair] Below are review comments from other members on your work. Handle them now: fix what you can directly in the files, and give a clear reason for anything you choose not to fix.',
  'prompt.fixLast': 'This is the final round of changes: the reviewer will check the result once more, but there will be no further chance to change it. Report briefly what you changed, what you did not, and why.',
  'prompt.fixTask': 'Your assigned work:\n{task}',
  'prompt.fixNotes': 'Review comments:\n{notes}',
  'prompt.fixFailedItem': '- **{name}**: {error}',

  'prompt.summary.failed': 'Execution failed for these members and their work was not reviewed. State this clearly in the summary:\n{list}',
  'prompt.summary.failedItem': '- {name}: {error}',
  'prompt.summary.reviewFailed': 'These cross-reviews did not complete, so the corresponding work was effectively unchecked. Mark it as "not reviewed" in the summary; do not describe it as problem-free:\n{list}',
  'prompt.summary.reviewFailedItem': '- {reviewer} reviewing {target}: {error}',
  'prompt.summary.fixFailed': 'The repair round failed for these members, so the issues the reviews raised still exist. List them as unresolved in the summary:\n{list}',
  'prompt.summary.fixFailedItem': '- {name}: {error}\n  Unaddressed review comments:\n{notes}',
  'prompt.summary.unresolved': 'These members cannot edit files, so their review comments are still unaddressed. List them in the summary and say what the user needs to do:\n{list}',
  'prompt.summary.unresolvedItem': '- {name}:\n{notes}',
  'prompt.summary.git': 'At the end of execution the git changes in the working directory were as follows. This is the **current state of the working tree** and may include changes that existed before this task started. Report it as is; do not claim all of these changes came from this task:\n{changes}',
  'prompt.summary.divide': '[Summary] As the lead, briefly summarize based on the execution reports, cross-reviews and repairs: what was completed, what the reviews found and fixed, and what remains unresolved or needs a decision from the user.',
  'prompt.summary.discuss': '[Summary] As the lead, briefly summarize the conclusions of this discussion, the points of disagreement, and the recommended next steps.',
  'git.more': '- ({n} more changed files not listed)',
  'git.preexisting': ' (already modified before execution)',

  'attach.header': (p) => `[Attachments] The user provided ${p.n} ${Number(p.n) === 1 ? 'attachment' : 'attachments'}:`,
  'attach.path': '- {label}\n  Path: {path}',
  'attach.imageInline': '- {label} (image attached to this message)',
  'attach.textInline': '- {label} (content below)',
  'attach.inlineCap': '- {label} (inline text limit reached, content omitted)',
  'attach.truncated': '\n…(file too long or attachment limit reached; truncated. See the original file for the full content)…',
  'attach.unreadable': 'Note: you cannot read the content of {names}. Do not guess from the file names; say so in your reply if needed.',

  'export.title': '# AI Roundtable conversation',
  'export.user': 'User',
  'export.agent': 'AI member',
  'export.system': 'System',
  'export.systemError': 'System error',
  'export.systemWarn': 'System warning',
  'export.timeUnknown': 'unknown time',
  'export.rawUsage': '> Raw usage: {fields}',
  'export.noFields': 'no fields',
  'export.usage': '> Usage: {fields}',
  'export.input': 'input: {n}',
  'export.cached': '{n} cached',
  'export.cacheWrite': '{n} cache write',
  'export.cachedInput': 'cached input: {n}',
  'export.output': 'output: {n}',
  'export.cost': 'cost: ${n}',
  'export.attachments': '> Attachments: {list}',
  'export.unreviewed': '> ⚠ Not reviewed: no other member checked this change — verify the diff yourself.',
  'export.error': '> Error: {text}',
  'export.empty': '_(no text)_',
  'phase.idle': 'Idle', 'phase.direct': 'Direct', 'phase.discuss': 'Discuss', 'phase.divide': 'Divide',
  'phase.tests': 'Write tests', 'phase.execute': 'Execute', 'phase.review': 'Review', 'phase.repair': 'Repair', 'phase.summary': 'Summary',

  'main.extNotFound': 'This API extension was not found. Save its settings first',
  'main.extNoTest': 'This extension does not support an API connection test',
  'main.nothingToExport': 'There is no conversation to export',
  'main.exportTitle': 'Export this conversation',
  'main.stillRunning': 'A task is still running. Stop it before loading a saved conversation',
  'main.attachFilter': 'Supported attachments',
  'terminal.noExpect': '/usr/bin/expect was not found on this Mac, so the terminal cannot open',
  'terminal.tooMany': 'Up to {max} terminal tabs can be open at once — close one first',
  'terminal.spawnFailed': 'The terminal could not start: {detail}',
  'adapter.missing': 'CLI "{cli}" not found: its extension may have been deleted or failed to load. Check Settings → CLIs & extensions',
  'adapter.failed': '{label} failed: {message}',
  // ---------- CLI member runtime messages ----------
  'proc.seconds': (p: Params) => `${p.n} second${Number(p.n) === 1 ? '' : 's'}`,
  'proc.minutes': (p: Params) => `${p.n} minute${Number(p.n) === 1 ? '' : 's'}`,
  'proc.minutesSeconds': '{m} min {s} s',
  'proc.timeout': 'Timed out ({time})',
  'proc.timeoutSigterm': 'Timed out ({time}); sent SIGTERM.',
  'proc.timeoutSigkill': 'The process was still running after the timeout; sent SIGKILL.',
  'proc.notFound': 'Command not found: {bin}',
  'proc.checkTimeout': 'timed out',
  'proc.checkSkipped': '(check skipped)',
  'cli.spawnFailed': 'Could not start {bin}: {detail}',
  'cli.timedOut': '{bin} timed out',
  'cli.exitCode': '{bin} exited with code {code}',
  'cli.failed': '{name} failed',
  'cli.reportedError': '{name} reported an error',
  'cli.turnFailed': 'The {name} turn failed',
  'cli.customNotSet': 'No custom command has been set',
  'cli.customCommand': 'the command',
  'cli.unparsableJson': 'Could not parse the JSON output: {detail}',
  'cli.loginHint': 'Installed, but not logged in. Open Terminal, run {cmd} and follow the prompts.',
  'cli.notLoggedIn': '{name} is not logged in, or the login has expired. Open Terminal, run {cmd}, follow the prompts, then try again.',
  'act.run': 'Run command: {detail}',
  'act.read': 'Read file: {detail}',
  'act.edit': 'Edit file: {detail}',
  'act.write': 'Write file: {detail}',
  'act.delete': 'Delete file: {detail}',
  'act.glob': 'Find files: {detail}',
  'act.grep': 'Search contents: {detail}',
  'act.ls': 'List folder: {detail}',
  'act.tool': 'Tool: {detail}',
  'act.changes': 'Edit files ({n})',
  'act.webSearch': 'Web search: {detail}',
  'cursor.effortIgnored': 'Cursor encodes effort in the model name, so {effort} was ignored',
  // ---------- Attachment rejection reasons (shown as "Could not attach the file: …") ----------
  'attachErr.notFormat': 'The content is not {fmt} (the extension does not match the actual content)',
  'attachErr.looksLike': 'The content looks like {kind}, not a text file',
  'attachErr.nul': 'Text files cannot contain NUL bytes (the content looks binary)',
  'attachErr.utf8': 'Text files must be valid UTF-8',
  'attachErr.json': 'The content is not valid JSON (the extension does not match the actual content)',
  'attachErr.tooBig': 'Over the {limit} per-file limit (this file is {size})',
  'attachErr.totalTooBig': 'Over the {limit} combined limit for one message',
  'attachErr.tooMany': 'At most {n} files at a time',
  'attachErr.unsupported': 'Unsupported file type "{ext}". Accepted types: {list}',
  'attachErr.noExt': 'no extension',
  'attachErr.empty': 'The file is empty',
  'attachErr.notFile': 'Not a regular file',
  'attachErr.unrecognized': 'The attachment content format was not recognised',
  'attachErr.noSource': 'No file content or path was given',
  'attachErr.badConversation': 'Invalid conversation ID',
  'attachErr.unsafeName': 'Could not create a safe storage name',
  'attachErr.exists': 'The attachment storage path already exists',
  'attachErr.unknownSize': 'unknown size',
  'attachErr.listSep': ', ',
  'bin.elf': 'an ELF executable',
  'bin.macho': 'a Mach-O executable',
  'bin.machoFat': 'a Mach-O universal binary',
  'bin.windows': 'a Windows executable',
  'bin.zip': 'a ZIP / Office archive',
  'bin.gzip': 'a gzip archive',
  // ---------- Conversation history ----------
  'session.notTranscript': 'This is not a conversation record',
  'session.noMessages': 'This is not a conversation record: the messages array is missing',
  'session.badId': 'Invalid record ID',
  'session.missing': 'This record no longer exists (it may have been deleted)',
  // ---------- Extension loading, saving and Ollama quick setup ----------
  'ext.duplicateId': 'id "{id}" is already used by {file}',
  'ext.badJson': 'Invalid JSON: {error}',
  'ext.badJsonUnsaved': 'Invalid JSON, not saved: {error}',
  'ext.badType': 'type must be "cli" or "openai" (write a .js plugin if you need more flexibility)',
  'ext.noRun': 'Must export a run(agent, ctx, kit) function',
  'ext.badFileName': 'File names may only contain letters, digits, . _ - and must end in .json or .js',
  'ext.badTemplate': 'Invalid template name',
  'ext.exists': 'An extension named {file} already exists',
  'ext.noUserDir': 'The extensions folder was not found',
  'ext.noTemplateDir': 'The built-in Ollama template folder was not found',
  'ext.ollamaTemplateUnreadable': 'Could not read the Ollama template: {error}',
  'ext.ollamaConfigUnreadable': 'Could not read the existing Ollama settings: {error}',
  'ext.ollamaModelMissing': 'Ollama does not have the model "{model}". Download it first and try again',
  // 只會嵌在 ext.legacyKeyFailed 的句子中間,所以小寫開頭
  'ext.noKeychain': 'the system keychain is unavailable',
  'ext.legacyKeyFailed': 'Found a legacy plain-text API key, but {error}. Set an environment variable and remove apiKey from the file',
  'ext.legacyKeyMigrated': 'Moved the legacy plain-text API key into the system keychain.',
  // ---------- Extension config validation errors ----------
  'spec.contentObject': 'The content must be an object',
  'spec.badId': 'id must be 1–64 letters, digits, . _ or -, starting with a letter or digit',
  'spec.modelsShape': 'models must be an array or "auto"',
  'spec.usageShape': 'usageShape must be {list}; leave it out to detect it from the fields',
  'spec.binShape': 'bin must be a command name or path',
  'spec.baseUrl': 'baseUrl must be a URL starting with http:// or https://',
  'spec.apiKeyEnv': 'apiKeyEnv must be an environment variable name',
  'spec.plainApiKey': 'The plain-text apiKey field is no longer supported; move the key into the API key field in the extension settings',
  'spec.mustBeObject': '{field} must be an object',
  'spec.mustBeArray': '{field} must be an array',
  'spec.mustBeString': '{field} must be a string',
  'spec.mustBeBoolean': '{field} must be a boolean',
  'spec.mustBePositive': '{field} must be a positive number',
  'spec.mustBePositiveInt': '{field} must be a positive integer',
  'spec.mustBeOneOf': '{field} must be {list}',
  'spec.onlyAccepts': '{field} only accepts {list}',
  'spec.noDuplicates': '{field} must not contain duplicates',
  'spec.badFormat': '{field} has an invalid format',
  'spec.badRegex': '{field} is not a valid regular expression: {error}',
  'spec.requiresTogether': '{b}=true must also be set explicitly when {a}=true',
  'spec.listSep': ', ',
  'spec.or': ' or ',
  // ---------- Counterexamples and the ratchet ----------
  'ce.untitled': '(untitled)',
  'ce.noOutput': '(no output)',
  'ce.stopped': 'Stopped',
  'ce.dropLimit': 'over the limit of 3 counterexamples per review',
  'ce.dropTooLong': 'counterexample too long',
  'ce.dropEmpty': 'counterexample was empty, or the block was never closed',
  'ce.fixNotes': '**These counterexamples were run by the app itself — they are not anyone\'s opinion.** Each one genuinely fails against the current code. After your fix they must all exit with code 0:\n\n{list}',
  'ce.fixItem': 'Counterexample "{title}" (raised by {reviewer}) currently fails with exit code {code}:\n```js\n{source}\n```\nOutput:\n```\n{output}\n```',
  'ce.status': 'The app re-ran the counterexamples:\n{list}',
  'ce.statusPassed': '- ✓ "{title}" now passes',
  'ce.statusFailed': '- ✗ "{title}" still fails:\n```\n{output}\n```',
  'ce.statusUnusable': '- ? "{title}" could not be run this time, so it is undecided:\n```\n{output}\n```',
  'ratchet.itemSyntax': '- file `{label}` no longer loads',
  'ratchet.itemGate': '- verify command `{label}`',
  'ratchet.itemCounterexample': '- counterexample "{label}"',
  'sys.baselineClean': 'Baseline: all {total} gates passed before the task started. Nothing from here on may turn any of them red.',
  'sys.baselineFailing': 'Baseline: {passed} of {total} gates passed before the task started. These were already failing, so they are not this task\'s responsibility — the ratchet compares whether things got worse, not whether everything passes:\n{list}',
  'sys.ceDropped': 'These counterexamples were not accepted:\n{list}',
  'sys.ceDroppedItem': '- "{title}" from {reviewer}: {reason}',
  'sys.ceItem': '- "{title}" (raised by {reviewer})',
  'sys.ceConfirmed': 'The app ran the counterexamples the reviewers attached; {n} of them genuinely reproduced a problem. They are the acceptance criteria for this repair round:\n{list}',
  'sys.ceUnsubstantiated': 'These counterexamples pass against the current code — the reviewer pointed at a problem but could not produce a reproducible case. They are not treated as things that must be fixed:\n{list}',
  'sys.ceUnusable': 'These counterexamples could not be run at all (write failed, timed out, or would not start), so they neither confirm nor clear anything:\n{list}',
  'sys.corpusSaved': 'Saved {n} confirmed counterexample(s) to this project\'s corpus ({total} in total), at `.roundtable/counterexamples.json` in the working directory. They will run again before every future task.',
  'sys.corpusFull': '{n} counterexample(s) were not saved: the corpus is full.',
  'sys.corpusFailed': 'Could not write the counterexample corpus: {error}',
  'sys.ratchetRegressed': '**Gates that went from passing to failing:**\n{list}',
  'sys.ratchetInherited': 'Some counterexamples carried over from the corpus now fail. They do not trigger an automatic rollback — an old counterexample can test the wrong requirement, and this task may be deliberately changing that behaviour — but please check:\n{list}',
  'sys.ratchetImproved': 'These gates went from failing to passing:\n{list}',
  'prompt.fixCounterexampleRule': 'Those counterexamples are the acceptance criteria for this round, and the app runs them itself: saying "fixed" does not count — the scripts have to actually exit with code 0. Do not modify the counterexamples themselves.',
  'prompt.reviewCounterexample': 'If you find a definite bug, attach an executable counterexample where you can: a fenced code block opening with ```counterexample (you may put a short title after the opening ```), containing a standalone Node.js script that requires or imports the changed file, calls it with concrete input, and throws when the behaviour is wrong (node:assert works well). The script runs from the top level of the working directory, so relative paths are just ./filename. It must fail against the current code; the app runs it once to check, and a counterexample that does not reproduce anything does not count. At most 3. If you cannot write an executable counterexample, plain prose is fine as before.',
};

const DICTS: Record<TextLocale, Record<string, Entry>> = { 'zh-Hant': ZH, en: EN };

export function tx(locale: TextLocale, key: string, params: Params = {}): string {
  const entry = DICTS[locale][key] ?? ZH[key];
  if (entry == null) return key;
  const text = typeof entry === 'function' ? entry(params) : entry;
  return text.replace(/\{(\w+)\}/g, (m, name: string) => (name in params ? String(params[name]) : m));
}

// 名稱清單的分隔符:中文用頓號,英文用逗號
export function joinNames(locale: TextLocale, names: readonly string[]): string {
  return names.join(locale === 'en' ? ', ' : '、');
}

// 中文用全形引號包名稱,英文用雙引號
export function quoteName(locale: TextLocale, name: string): string {
  return locale === 'en' ? `"${name}"` : `「${name}」`;
}
